// generated by: ./font_encode.py -i nokia_large.py (don't edit)
#include "lcd.h"
static const uint32_t nokia_large_00[] = { 0x0, };
static const uint32_t nokia_large_20[] = { 0x00000000, };
static const uint32_t nokia_large_21[] = { 0xffff3c00, };
static const uint32_t nokia_large_22[] = { 0x99990000, };
static const uint32_t nokia_large_23[] = { 0x6cd9b7f6, 0xdfdb366c, };
static const uint32_t nokia_large_24[] = { 0x10fb5e8d, 0x0f858b17, 0xadf08100, };
static const uint32_t nokia_large_25[] = { 0x474ab241, 0x820c126a, 0x97100000, };
static const uint32_t nokia_large_26[] = { 0x70d8d8d8, 0xd872f6dc, 0xccde7300, };
static const uint32_t nokia_large_27[] = { 0xe0000000, };
static const uint32_t nokia_large_28[] = { 0x2d6db6d9, 0x32000000, };
static const uint32_t nokia_large_29[] = { 0x9936db6d, 0x68000000, };
static const uint32_t nokia_large_2a[] = { 0x44d8e7f3, 0x8d910000, };
static const uint32_t nokia_large_2b[] = { 0x30cfcc30, };
static const uint32_t nokia_large_2c[] = { 0x6f000000, };
static const uint32_t nokia_large_2d[] = { 0xffc00000, };
static const uint32_t nokia_large_2e[] = { 0xf0000000, };
static const uint32_t nokia_large_2f[] = { 0x18cc6331, 0x8cc63000, };
static const uint32_t nokia_large_30[] = { 0x7d8f1e3c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_31[] = { 0x37fb3333, 0x33300000, };
static const uint32_t nokia_large_32[] = { 0x7d8f1830, 0x639c60c1, 0x83f80000, };
static const uint32_t nokia_large_33[] = { 0x7d8c1833, 0xc0c18307, 0x8df00000, };
static const uint32_t nokia_large_34[] = { 0x041871e6, 0xd9b37f0c, 0x18300000, };
static const uint32_t nokia_large_35[] = { 0xfd83060f, 0xd8c18307, 0x8df00000, };
static const uint32_t nokia_large_36[] = { 0x7d8f060f, 0xd8f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_37[] = { 0xfc30c618, 0xc3186186, 0x00000000, };
static const uint32_t nokia_large_38[] = { 0x7d8f1e37, 0xd8f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_39[] = { 0x7d8f1e3c, 0x78df8307, 0x8df00000, };
static const uint32_t nokia_large_3a[] = { 0xf03c0000, };
static const uint32_t nokia_large_3b[] = { 0x6c00de00, };
static const uint32_t nokia_large_3c[] = { 0x08cccc30, 0xc3080000, };
static const uint32_t nokia_large_3d[] = { 0xf801f000, };
static const uint32_t nokia_large_3e[] = { 0x86186199, 0x98800000, };
static const uint32_t nokia_large_3f[] = { 0x7a38c30c, 0x630c00c3, 0x00000000, };
static const uint32_t nokia_large_40[] = { 0x3e20a535, 0x9a4d2693, 0x4a9a204f, 0xc0000000, };
static const uint32_t nokia_large_41[] = { 0x7d8f1e3c, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_42[] = { 0xfd8f1e3f, 0xd8f1e3c7, 0x8ff00000, };
static const uint32_t nokia_large_43[] = { 0x7b3c30c3, 0x0c30c337, 0x80000000, };
static const uint32_t nokia_large_44[] = { 0xf99b1e3c, 0x78f1e3c7, 0x9be00000, };
static const uint32_t nokia_large_45[] = { 0xff83060f, 0x983060c1, 0x83f80000, };
static const uint32_t nokia_large_46[] = { 0xff83060f, 0x983060c1, 0x83000000, };
static const uint32_t nokia_large_47[] = { 0x7d8f060c, 0x19f1e3c7, 0x8df80000, };
static const uint32_t nokia_large_48[] = { 0xc78f1e3f, 0xf8f1e3c7, 0x8f180000, };
static const uint32_t nokia_large_49[] = { 0xfffffc00, };
static const uint32_t nokia_large_4a[] = { 0x18c6318c, 0x631cdc00, };
static const uint32_t nokia_large_4b[] = { 0xc79b678e, 0x1c3c6ccd, 0x8f080000, };
static const uint32_t nokia_large_4c[] = { 0xc30c30c3, 0x0c30c30f, 0xc0000000, };
static const uint32_t nokia_large_4d[] = { 0x80e0f8fe, 0xfdde4f07, 0x83c1e0f0, 0x60000000, };
static const uint32_t nokia_large_4e[] = { 0xc78f9f3f, 0x7af7e7cf, 0x8f180000, };
static const uint32_t nokia_large_4f[] = { 0x7ec3c3c3, 0xc3c3c3c3, 0xc3c37e00, };
static const uint32_t nokia_large_50[] = { 0xfd8f1e3c, 0x78ff60c1, 0x83000000, };
static const uint32_t nokia_large_51[] = { 0x7ec3c3c3, 0xc3c3c3c3, 0xd3db7e06, 0x02000000, };
static const uint32_t nokia_large_52[] = { 0xfd8f1e3c, 0x78ff6ccd, 0x8f080000, };
static const uint32_t nokia_large_53[] = { 0x7b3c30c1, 0xe0c30f37, 0x80000000, };
static const uint32_t nokia_large_54[] = { 0xfcc30c30, 0xc30c30c3, 0x00000000, };
static const uint32_t nokia_large_55[] = { 0xc78f1e3c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_56[] = { 0xc3c3c3c3, 0x66666624, 0x3c181800, };
static const uint32_t nokia_large_57[] = { 0xc0f03c0f, 0x03619b66, 0xd9b63f0c, 0xc3300000, };
static const uint32_t nokia_large_58[] = { 0xc78f1b66, 0xc71b36c7, 0x8f180000, };
static const uint32_t nokia_large_59[] = { 0xc3c36666, 0x3c3c1818, 0x18181800, };
static const uint32_t nokia_large_5a[] = { 0xfe0c38e3, 0x8e3860c1, 0x83f80000, };
static const uint32_t nokia_large_5b[] = { 0xfccccccc, 0xccccf000, };
static const uint32_t nokia_large_5d[] = { 0xf3333333, 0x3333f000, };
static const uint32_t nokia_large_5f[] = { 0xfc000000, };
static const uint32_t nokia_large_61[] = { 0x7830dfcf, 0x3cdf0000, };
static const uint32_t nokia_large_62[] = { 0xc30c3ecf, 0x3cf3cf3f, 0x80000000, };
static const uint32_t nokia_large_63[] = { 0x76718c63, 0x2e000000, };
static const uint32_t nokia_large_64[] = { 0x0c30dfcf, 0x3cf3cf37, 0xc0000000, };
static const uint32_t nokia_large_65[] = { 0x7b3cffc3, 0x0c5e0000, };
static const uint32_t nokia_large_66[] = { 0x366f6666, 0x66600000, };
static const uint32_t nokia_large_67[] = { 0x7f3cf3cf, 0x3cdf0de0, };
static const uint32_t nokia_large_68[] = { 0xc30c3ecf, 0x3cf3cf3c, 0xc0000000, };
static const uint32_t nokia_large_69[] = { 0xf3fffc00, };
static const uint32_t nokia_large_6a[] = { 0x6c36db6d, 0xbc000000, };
static const uint32_t nokia_large_6b[] = { 0xc30c33db, 0xce38f36c, 0xc0000000, };
static const uint32_t nokia_large_6c[] = { 0xfffffc00, };
static const uint32_t nokia_large_6d[] = { 0xfedbdbdb, 0xdbdbdbdb, };
static const uint32_t nokia_large_6e[] = { 0xfb3cf3cf, 0x3cf30000, };
static const uint32_t nokia_large_6f[] = { 0x7b3cf3cf, 0x3cde0000, };
static const uint32_t nokia_large_70[] = { 0xfb3cf3cf, 0x3cfec300, };
static const uint32_t nokia_large_71[] = { 0x7f3cf3cf, 0x3cdf0c30, };
static const uint32_t nokia_large_72[] = { 0xdff18c63, 0x18000000, };
static const uint32_t nokia_large_73[] = { 0x7e38e38c, 0x7e000000, };
static const uint32_t nokia_large_74[] = { 0x666f6666, 0x66300000, };
static const uint32_t nokia_large_75[] = { 0xcf3cf3cf, 0x3cdf0000, };
static const uint32_t nokia_large_76[] = { 0xcf3cf349, 0xe30c0000, };
static const uint32_t nokia_large_77[] = { 0xc1e0f06c, 0x66b3f8d8, 0x6c000000, };
static const uint32_t nokia_large_78[] = { 0xcf378c31, 0xecf30000, };
static const uint32_t nokia_large_79[] = { 0xcf3cf3cf, 0x3cdf0de0, };
static const uint32_t nokia_large_7a[] = { 0xfc31ce73, 0x8c3f0000, };
static const uint32_t nokia_large_c0[] = { 0x6061f63c, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_c1[] = { 0x0c31f63c, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_c2[] = { 0x38d803ec, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_c4[] = { 0x6c01f63c, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_c5[] = { 0x105043ec, 0x78f1ffc7, 0x8f180000, };
static const uint32_t nokia_large_c6[] = { 0x7ff8c318, 0x630c7dfc, 0x318630c6, 0x18c31d80, };
static const uint32_t nokia_large_c7[] = { 0x7b3c30c3, 0x0c30c337, 0x8c600000, };
static const uint32_t nokia_large_c8[] = { 0x6063fe0c, 0x1f3060c1, 0x83f80000, };
static const uint32_t nokia_large_c9[] = { 0x0c33fe0c, 0x1f3060c1, 0x83f80000, };
static const uint32_t nokia_large_ca[] = { 0x38d807fc, 0x183e60c1, 0x83f80000, };
static const uint32_t nokia_large_cb[] = { 0x6c03fe0c, 0x1f3060c1, 0x83f80000, };
static const uint32_t nokia_large_cc[] = { 0x93fffc00, };
static const uint32_t nokia_large_cd[] = { 0x63fffc00, };
static const uint32_t nokia_large_ce[] = { 0x546db6db, 0x00000000, };
static const uint32_t nokia_large_cf[] = { 0xa36db6db, 0x00000000, };
static const uint32_t nokia_large_d1[] = { 0x34b31f3e, 0x7ef5efcf, 0x87180000, };
static const uint32_t nokia_large_d2[] = { 0x30187ec3, 0xc3c3c3c3, 0xc3c37e00, };
static const uint32_t nokia_large_d3[] = { 0x0c187ec3, 0xc3c3c3c3, 0xc3c37e00, };
static const uint32_t nokia_large_d4[] = { 0x1c36007e, 0xc3c3c3c3, 0xc3c37e00, };
static const uint32_t nokia_large_d6[] = { 0x36007ec3, 0xc3c3c3c3, 0xc3c37e00, };
static const uint32_t nokia_large_d8[] = { 0x3f586619, 0x8e659a67, 0x198661af, 0xc0000000, };
static const uint32_t nokia_large_d9[] = { 0x30331e3c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_da[] = { 0x18631e3c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_db[] = { 0x38d8063c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_dc[] = { 0x6c031e3c, 0x78f1e3c7, 0x8df00000, };
static const uint32_t nokia_large_df[] = { 0x7d8f1e3d, 0xd8f1e3c7, 0xaf700000, };
static const uint32_t nokia_large_e0[] = { 0x60c01e0c, 0x37f3cf37, 0xc0000000, };
static const uint32_t nokia_large_e1[] = { 0x18c01e0c, 0x37f3cf37, 0xc0000000, };
static const uint32_t nokia_large_e2[] = { 0x39b01e0c, 0x37f3cf37, 0xc0000000, };
static const uint32_t nokia_large_e4[] = { 0x6c07830d, 0xfcf3cdf0, };
static const uint32_t nokia_large_e5[] = { 0x10a11e0c, 0x37f3cf37, 0xc0000000, };
static const uint32_t nokia_large_e6[] = { 0x7f8330cd, 0xffcc330c, 0xc5fe0000, };
static const uint32_t nokia_large_e7[] = { 0x76718c63, 0x2e330000, };
static const uint32_t nokia_large_e8[] = { 0x60c01ecf, 0x3ff0c317, 0x80000000, };
static const uint32_t nokia_large_e9[] = { 0x18c01ecf, 0x3ff0c317, 0x80000000, };
static const uint32_t nokia_large_ea[] = { 0x39b01ecf, 0x3ff0c317, 0x80000000, };
static const uint32_t nokia_large_eb[] = { 0x6c07b3cf, 0xfc30c5e0, };
static const uint32_t nokia_large_ec[] = { 0x93fffc00, };
static const uint32_t nokia_large_ed[] = { 0x63fffc00, };
static const uint32_t nokia_large_ee[] = { 0x546db6db, 0x00000000, };
static const uint32_t nokia_large_ef[] = { 0xa36db6d8, };
static const uint32_t nokia_large_f1[] = { 0x35603ecf, 0x3cf3cf3c, 0xc0000000, };
static const uint32_t nokia_large_f2[] = { 0x60c01ecf, 0x3cf3cf37, 0x80000000, };
static const uint32_t nokia_large_f3[] = { 0x18c01ecf, 0x3cf3cf37, 0x80000000, };
static const uint32_t nokia_large_f4[] = { 0x39b01ecf, 0x3cf3cf37, 0x80000000, };
static const uint32_t nokia_large_f6[] = { 0x6c07b3cf, 0x3cf3cde0, };
static const uint32_t nokia_large_f8[] = { 0x3d66666e, 0x766666bc, };
static const uint32_t nokia_large_f9[] = { 0x60c033cf, 0x3cf3cf37, 0xc0000000, };
static const uint32_t nokia_large_fa[] = { 0x18c033cf, 0x3cf3cf37, 0xc0000000, };
static const uint32_t nokia_large_fb[] = { 0x39b033cf, 0x3cf3cf37, 0xc0000000, };
static const uint32_t nokia_large_fc[] = { 0x6c0cf3cf, 0x3cf3cdf0, };

const struct font nokia_large = {
	.ascent = 12,
	.descent = -2,
	.glyphs = {
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x00
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x01
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x02
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x03
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x04
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x05
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x06
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x07
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x08
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x09
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0a
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0c
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0e
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x0f
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x10
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x11
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x12
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x13
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x14
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x15
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x16
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x17
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x18
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x19
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1a
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1c
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1e
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x1f
		   {3, 1, 0, 0, 4, nokia_large_20},	// 0x20
		   {2, 11, 0, 0, 3, nokia_large_21},	// 0x21
		   {4, 4, 0, 7, 5, nokia_large_22},	// 0x22
		   {7, 9, 0, 2, 8, nokia_large_23},	// 0x23
		   {7, 13, 0, -1, 8, nokia_large_24},	// 0x24
		   {7, 11, 0, 0, 8, nokia_large_25},	// 0x25
		   {8, 11, 0, 0, 9, nokia_large_26},	// 0x26
		   {1, 3, 0, 9, 2, nokia_large_27},	// 0x27
		   {3, 13, 0, -1, 4, nokia_large_28},	// 0x28
		   {3, 13, 0, -1, 4, nokia_large_29},	// 0x29
		   {7, 7, 0, 2, 8, nokia_large_2a},	// 0x2a
		   {6, 5, 0, 3, 7, nokia_large_2b},	// 0x2b
		   {3, 3, 0, -1, 4, nokia_large_2c},	// 0x2c
		   {5, 2, 0, 4, 6, nokia_large_2d},	// 0x2d
		   {2, 2, 0, 0, 3, nokia_large_2e},	// 0x2e
		   {5, 11, 0, 0, 6, nokia_large_2f},	// 0x2f
		   {7, 11, 0, 0, 8, nokia_large_30},	// 0x30
		   {4, 11, 0, 0, 5, nokia_large_31},	// 0x31
		   {7, 11, 0, 0, 8, nokia_large_32},	// 0x32
		   {7, 11, 0, 0, 8, nokia_large_33},	// 0x33
		   {7, 11, 0, 0, 8, nokia_large_34},	// 0x34
		   {7, 11, 0, 0, 8, nokia_large_35},	// 0x35
		   {7, 11, 0, 0, 8, nokia_large_36},	// 0x36
		   {6, 11, 0, 0, 7, nokia_large_37},	// 0x37
		   {7, 11, 0, 0, 8, nokia_large_38},	// 0x38
		   {7, 11, 0, 0, 8, nokia_large_39},	// 0x39
		   {2, 7, 0, 1, 3, nokia_large_3a},	// 0x3a
		   {3, 8, 0, 0, 4, nokia_large_3b},	// 0x3b
		   {5, 9, 0, 1, 6, nokia_large_3c},	// 0x3c
		   {5, 4, 0, 3, 6, nokia_large_3d},	// 0x3d
		   {5, 9, 0, 1, 6, nokia_large_3e},	// 0x3e
		   {6, 11, 0, 0, 7, nokia_large_3f},	// 0x3f
		   {9, 11, 0, 0, 10, nokia_large_40},	// 0x40
		   {7, 11, 0, 0, 8, nokia_large_41},	// 0x41
		   {7, 11, 0, 0, 8, nokia_large_42},	// 0x42
		   {6, 11, 0, 0, 7, nokia_large_43},	// 0x43
		   {7, 11, 0, 0, 8, nokia_large_44},	// 0x44
		   {7, 11, 0, 0, 8, nokia_large_45},	// 0x45
		   {7, 11, 0, 0, 8, nokia_large_46},	// 0x46
		   {7, 11, 0, 0, 8, nokia_large_47},	// 0x47
		   {7, 11, 0, 0, 8, nokia_large_48},	// 0x48
		   {2, 11, 0, 0, 3, nokia_large_49},	// 0x49
		   {5, 11, 0, 0, 6, nokia_large_4a},	// 0x4a
		   {7, 11, 0, 0, 8, nokia_large_4b},	// 0x4b
		   {6, 11, 0, 0, 7, nokia_large_4c},	// 0x4c
		   {9, 11, 0, 0, 10, nokia_large_4d},	// 0x4d
		   {7, 11, 0, 0, 8, nokia_large_4e},	// 0x4e
		   {8, 11, 0, 0, 9, nokia_large_4f},	// 0x4f
		   {7, 11, 0, 0, 8, nokia_large_50},	// 0x50
		   {8, 13, 0, -2, 9, nokia_large_51},	// 0x51
		   {7, 11, 0, 0, 8, nokia_large_52},	// 0x52
		   {6, 11, 0, 0, 7, nokia_large_53},	// 0x53
		   {6, 11, 0, 0, 7, nokia_large_54},	// 0x54
		   {7, 11, 0, 0, 8, nokia_large_55},	// 0x55
		   {8, 11, 0, 0, 9, nokia_large_56},	// 0x56
		   {10, 11, 0, 0, 11, nokia_large_57},	// 0x57
		   {7, 11, 0, 0, 8, nokia_large_58},	// 0x58
		   {8, 11, 0, 0, 9, nokia_large_59},	// 0x59
		   {7, 11, 0, 0, 8, nokia_large_5a},	// 0x5a
		   {4, 13, 0, 0, 5, nokia_large_5b},	// 0x5b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x5c
		   {4, 13, 0, 0, 5, nokia_large_5d},	// 0x5d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x5e
		   {6, 1, 0, 0, 7, nokia_large_5f},	// 0x5f
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x60
		   {6, 8, 0, 0, 7, nokia_large_61},	// 0x61
		   {6, 11, 0, 0, 7, nokia_large_62},	// 0x62
		   {5, 8, 0, 0, 6, nokia_large_63},	// 0x63
		   {6, 11, 0, 0, 7, nokia_large_64},	// 0x64
		   {6, 8, 0, 0, 7, nokia_large_65},	// 0x65
		   {4, 11, 0, 0, 5, nokia_large_66},	// 0x66
		   {6, 10, 0, -2, 7, nokia_large_67},	// 0x67
		   {6, 11, 0, 0, 7, nokia_large_68},	// 0x68
		   {2, 11, 0, 0, 3, nokia_large_69},	// 0x69
		   {3, 13, 0, -2, 4, nokia_large_6a},	// 0x6a
		   {6, 11, 0, 0, 7, nokia_large_6b},	// 0x6b
		   {2, 11, 0, 0, 3, nokia_large_6c},	// 0x6c
		   {8, 8, 0, 0, 9, nokia_large_6d},	// 0x6d
		   {6, 8, 0, 0, 7, nokia_large_6e},	// 0x6e
		   {6, 8, 0, 0, 7, nokia_large_6f},	// 0x6f
		   {6, 10, 0, -2, 7, nokia_large_70},	// 0x70
		   {6, 10, 0, -2, 7, nokia_large_71},	// 0x71
		   {5, 8, 0, 0, 6, nokia_large_72},	// 0x72
		   {5, 8, 0, 0, 6, nokia_large_73},	// 0x73
		   {4, 11, 0, 0, 5, nokia_large_74},	// 0x74
		   {6, 8, 0, 0, 7, nokia_large_75},	// 0x75
		   {6, 8, 0, 0, 7, nokia_large_76},	// 0x76
		   {9, 8, 0, 0, 10, nokia_large_77},	// 0x77
		   {6, 8, 0, 0, 7, nokia_large_78},	// 0x78
		   {6, 10, 0, -2, 7, nokia_large_79},	// 0x79
		   {6, 8, 0, 0, 7, nokia_large_7a},	// 0x7a
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x7b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x7c
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x7d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x7e
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x7f
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x80
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x81
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x82
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x83
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x84
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x85
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x86
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x87
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x88
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x89
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8a
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8c
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8e
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x8f
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x90
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x91
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x92
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x93
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x94
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x95
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x96
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x97
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x98
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x99
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9a
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9b
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9c
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9d
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9e
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0x9f
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa0
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa1
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa2
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa3
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa4
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa5
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa6
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa7
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa8
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xa9
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xaa
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xab
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xac
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xad
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xae
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xaf
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb0
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb1
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb2
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb3
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb4
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb5
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb6
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb7
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb8
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xb9
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xba
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xbb
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xbc
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xbd
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xbe
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xbf
		   {7, 11, 0, 0, 8, nokia_large_c0},	// 0xc0
		   {7, 11, 0, 0, 8, nokia_large_c1},	// 0xc1
		   {7, 11, 0, 0, 8, nokia_large_c2},	// 0xc2
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xc3
		   {7, 11, 0, 0, 8, nokia_large_c4},	// 0xc4
		   {7, 11, 0, 0, 8, nokia_large_c5},	// 0xc5
		   {11, 11, 0, 0, 12, nokia_large_c6},	// 0xc6
		   {6, 13, 0, 0, 7, nokia_large_c7},	// 0xc7
		   {7, 11, 0, 0, 8, nokia_large_c8},	// 0xc8
		   {7, 11, 0, 0, 8, nokia_large_c9},	// 0xc9
		   {7, 11, 0, 0, 8, nokia_large_ca},	// 0xca
		   {7, 11, 0, 0, 8, nokia_large_cb},	// 0xcb
		   {2, 11, 0, 0, 3, nokia_large_cc},	// 0xcc
		   {2, 11, 0, 0, 3, nokia_large_cd},	// 0xcd
		   {3, 11, 0, 0, 4, nokia_large_ce},	// 0xce
		   {3, 11, 0, 0, 4, nokia_large_cf},	// 0xcf
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xd0
		   {7, 11, 0, 0, 8, nokia_large_d1},	// 0xd1
		   {8, 11, 0, 0, 9, nokia_large_d2},	// 0xd2
		   {8, 11, 0, 0, 9, nokia_large_d3},	// 0xd3
		   {8, 11, 0, 0, 9, nokia_large_d4},	// 0xd4
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xd5
		   {8, 11, 0, 0, 9, nokia_large_d6},	// 0xd6
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xd7
		   {10, 10, 0, 1, 11, nokia_large_d8},	// 0xd8
		   {7, 11, 0, 0, 8, nokia_large_d9},	// 0xd9
		   {7, 11, 0, 0, 8, nokia_large_da},	// 0xda
		   {7, 11, 0, 0, 8, nokia_large_db},	// 0xdb
		   {7, 11, 0, 0, 8, nokia_large_dc},	// 0xdc
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xdd
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xde
		   {7, 11, 0, 0, 8, nokia_large_df},	// 0xdf
		   {6, 11, 0, 0, 7, nokia_large_e0},	// 0xe0
		   {6, 11, 0, 0, 7, nokia_large_e1},	// 0xe1
		   {6, 11, 0, 0, 7, nokia_large_e2},	// 0xe2
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xe3
		   {6, 10, 0, 0, 7, nokia_large_e4},	// 0xe4
		   {6, 11, 0, 0, 7, nokia_large_e5},	// 0xe5
		   {10, 8, 0, 0, 11, nokia_large_e6},	// 0xe6
		   {5, 10, 0, 0, 6, nokia_large_e7},	// 0xe7
		   {6, 11, 0, 0, 7, nokia_large_e8},	// 0xe8
		   {6, 11, 0, 0, 7, nokia_large_e9},	// 0xe9
		   {6, 11, 0, 0, 7, nokia_large_ea},	// 0xea
		   {6, 10, 0, 0, 7, nokia_large_eb},	// 0xeb
		   {2, 11, 0, 0, 3, nokia_large_ec},	// 0xec
		   {2, 11, 0, 0, 3, nokia_large_ed},	// 0xed
		   {3, 11, 0, 0, 4, nokia_large_ee},	// 0xee
		   {3, 10, 0, 0, 4, nokia_large_ef},	// 0xef
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xf0
		   {6, 11, 0, 0, 7, nokia_large_f1},	// 0xf1
		   {6, 11, 0, 0, 7, nokia_large_f2},	// 0xf2
		   {6, 11, 0, 0, 7, nokia_large_f3},	// 0xf3
		   {6, 11, 0, 0, 7, nokia_large_f4},	// 0xf4
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xf5
		   {6, 10, 0, 0, 7, nokia_large_f6},	// 0xf6
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xf7
		   {8, 8, 0, 0, 9, nokia_large_f8},	// 0xf8
		   {6, 11, 0, 0, 7, nokia_large_f9},	// 0xf9
		   {6, 11, 0, 0, 7, nokia_large_fa},	// 0xfa
		   {6, 11, 0, 0, 7, nokia_large_fb},	// 0xfb
		   {6, 10, 0, 0, 7, nokia_large_fc},	// 0xfc
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xfd
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xfe
		   {0, 0, 0, 0, 0, nokia_large_00},	// 0xff
		   },
};
