// generated by: ./bdf2ggm -i profont29.bdf (don't edit)
// Copyright: "ProFont Distribution 2.2 Ñ Generated by Fontographer 4.1.5"
#include "lcd.h"
static const uint32_t profont29_21[] = { 0xffffffff, 0xffc0ff80, };
static const uint32_t profont29_22[] = { 0xe3f1f8fc, 0x7e3f1f8f, 0xc7e38000, };
static const uint32_t profont29_23[] = { 0x1c7038e0, 0x71c7ffff, 0xffffffc7, 0x1c0e381c, 0x71ffffff, 0xfffff1c7, 0x038e071c, 0x00000000, };
static const uint32_t profont29_24[] = { 0x07003801, 0xc01f03fe, 0x3ff9dddc, 0xe7e73f38, 0x1dc0ff03, 0xfe07f81d, 0xc0e7e73f, 0x39dddcff, 0xe3fe07c0, 0x1c00e007, 0x00000000, };
static const uint32_t profont29_25[] = { 0x1ffcfff7, 0xffd987e7, 0x3f9dee7f, 0x19f87fe0, 0xff01ff07, 0xcc3f39fc, 0xef73b8cc, 0xe3f3878e, 0x0c000000, };
static const uint32_t profont29_26[] = { 0x0f00ff07, 0xfe1c38e1, 0xe38f0e78, 0x1fc07e00, 0xf007e09f, 0xc7e7bf8f, 0xee1f1c7c, 0x7ff8fef0, 0xe1800000, };
static const uint32_t profont29_27[] = { 0xffffffe0, };
static const uint32_t profont29_28[] = { 0x0303c3c3, 0xc3c3c3c1, 0xc0e07038, 0x1c0e0703, 0x81c0e070, 0x3c0f03c0, 0xf03c0f03, 0x00000000, };
static const uint32_t profont29_29[] = { 0x60781e07, 0x81e0781e, 0x070381c0, 0xe070381c, 0x0e070381, 0xc1e1e1e1, 0xe1e1e060, 0x00000000, };
static const uint32_t profont29_2a[] = { 0x07003819, 0xcdeff7ff, 0x0fe07f0f, 0xfefffb39, 0x81c00e00, 0x70000000, };
static const uint32_t profont29_2b[] = { 0x07003801, 0xc00e0070, 0x7fffffff, 0xff070038, 0x01c00e00, 0x70000000, };
static const uint32_t profont29_2c[] = { 0x39f7df3c, 0x71cf7bc6, 0x00000000, };
static const uint32_t profont29_2d[] = { 0xffffff00, };
static const uint32_t profont29_2e[] = { 0x77fff700, };
static const uint32_t profont29_2f[] = { 0x000e001c, 0x007000e0, 0x03800700, 0x1c003800, 0xe001c007, 0x000e0038, 0x007001c0, 0x03800e00, 0x1c007000, 0xe0038007, 0x001c0038, 0x00e001c0, 0x00000000, };
static const uint32_t profont29_30[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x3f81fe0f, 0xf87fe3df, 0x9e7ef1ff, 0x87fc1fe0, 0x7f01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_31[] = { 0x07003803, 0xc0fe07f0, 0x3f801c00, 0xe0070038, 0x01c00e00, 0x7003801c, 0x00e0ffff, 0xfffffe00, };
static const uint32_t profont29_32[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807001, 0xc00e0078, 0x03c01e00, 0xf007803c, 0x01e00f00, 0x7fffffff, 0xffc00000, };
static const uint32_t profont29_33[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807001, 0xc01e03f0, 0x0f803f00, 0x1e001f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_34[] = { 0x00e00780, 0x3e01f80f, 0xe07b83ce, 0x1e38f0e3, 0x838fffff, 0xfffffc03, 0x800e0038, 0x07fc1ff0, 0x7fc00000, };
static const uint32_t profont29_35[] = { 0xffffffff, 0xfff800e0, 0x03ff0fff, 0x3ffe0038, 0x007001c0, 0x07001f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_36[] = { 0x0fe0ff87, 0xfe1c00e0, 0x03ff0fff, 0x3ffee03b, 0x807e01f8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_37[] = { 0xffffffff, 0xffc00700, 0x1c007003, 0xc01e00f0, 0x07803c01, 0xe007001c, 0x007001c0, 0x07001c00, 0x70000000, };
static const uint32_t profont29_38[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e01, 0xde1e3ff0, 0x7f83ff1e, 0x1ee01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_39[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e01, 0xf807e01f, 0x807701df, 0xff3ffc3f, 0xf001c00e, 0x1ff87fc1, 0xfc000000, };
static const uint32_t profont29_3a[] = { 0x77fff700, 0x0077fff7, 0x00000000, };
static const uint32_t profont29_3b[] = { 0x39f7df38, 0x000039f7, 0xdf3c71cf, 0x7bc60000, };
static const uint32_t profont29_3c[] = { 0x00600f01, 0xe03c0780, 0xf01e03c0, 0x780f0078, 0x03c01e00, 0xf007803c, 0x01e00f00, 0x60000000, };
static const uint32_t profont29_3d[] = { 0xffffffff, 0xffc00000, 0x00000fff, 0xfffffffc, };
static const uint32_t profont29_3e[] = { 0x600f0078, 0x03c01e00, 0xf007803c, 0x01e00f01, 0xe03c0780, 0xf01e03c0, 0x780f0060, 0x00000000, };
static const uint32_t profont29_3f[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807001, 0xc00f0078, 0x03c01e00, 0xf007801c, 0x00000000, 0x07001c00, 0x70000000, };
static const uint32_t profont29_40[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f87fe3f, 0xf9ffe71f, 0x9c7e71f9, 0xffe3fb87, 0xce001c00, 0x7ffcfff0, 0xffc00000, };
static const uint32_t profont29_41[] = { 0x07801e00, 0xfc03f01c, 0xe0738387, 0x0e1c7039, 0xc0ee01ff, 0xffffffff, 0xfe01f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_42[] = { 0xffc3ffcf, 0xffb80ee0, 0x1f807e01, 0xf81efff3, 0xff8fff38, 0x1ee01f80, 0x7e01f80e, 0xfffbffcf, 0xfc000000, };
static const uint32_t profont29_43[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x3800e003, 0x800e0038, 0x00e00380, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_44[] = { 0xffc3ffcf, 0xffb80ee0, 0x1f807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01f80e, 0xfffbffcf, 0xfc000000, };
static const uint32_t profont29_45[] = { 0xffffffff, 0xfff800e0, 0x03800e00, 0x3800ffe3, 0xff8ffe38, 0x00e00380, 0x0e003800, 0xffffffff, 0xffc00000, };
static const uint32_t profont29_46[] = { 0xffffffff, 0xfff800e0, 0x03800e00, 0x3800ffe3, 0xff8ffe38, 0x00e00380, 0x0e003800, 0xe003800e, 0x00000000, };
static const uint32_t profont29_47[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x3800e0ff, 0x83fe0ff8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_48[] = { 0xe01f807e, 0x01f807e0, 0x1f807e01, 0xf807ffff, 0xfffffff8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_49[] = { 0xffffffff, 0xfe0e0070, 0x03801c00, 0xe0070038, 0x01c00e00, 0x7003801c, 0x00e0ffff, 0xfffffe00, };
static const uint32_t profont29_4a[] = { 0x001c0070, 0x01c00700, 0x1c007001, 0xc007001c, 0x007001f8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_4b[] = { 0xe03f03f8, 0x3dc3ce3c, 0x73c3bc1f, 0xc0fc07c0, 0x3f01fc0e, 0xf073c38f, 0x1c3ce0f7, 0x03f80e00, };
static const uint32_t profont29_4c[] = { 0xe003800e, 0x003800e0, 0x03800e00, 0x3800e003, 0x800e0038, 0x00e00380, 0x0e003800, 0xffffffff, 0xffc00000, };
static const uint32_t profont29_4d[] = { 0xe00fe03f, 0xe0ffe3ff, 0xeffdfdf9, 0xf3f1c7e3, 0x8fc71f8e, 0x3f007e00, 0xfc01f803, 0xf007e00f, 0xc01f8038, };
static const uint32_t profont29_4e[] = { 0xe01fc07f, 0x81ff07fe, 0x1fbc7e79, 0xf8f7e1ff, 0x83fe07f8, 0x0fe01f80, 0x7e01f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_4f[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_50[] = { 0xffc3ffcf, 0xffb80ee0, 0x1f807e01, 0xf80efffb, 0xffcffc38, 0x00e00380, 0x0e003800, 0xe003800e, 0x00000000, };
static const uint32_t profont29_51[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e01, 0xf807e01f, 0x807e01f8, 0x07e01f98, 0x7ef1ddfe, 0x7ff8ffc0, 0xff001e00, 0x3c006000, };
static const uint32_t profont29_52[] = { 0xffc3ffcf, 0xffb80ee0, 0x1f807e01, 0xf81efff3, 0xff8fff38, 0x1ee01f80, 0x7e01f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_53[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x1c007fc0, 0xffc0ff80, 0x0e001f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_54[] = { 0xffffffff, 0xfe0e0070, 0x03801c00, 0xe0070038, 0x01c00e00, 0x7003801c, 0x00e00700, 0x3801c000, };
static const uint32_t profont29_55[] = { 0xe01f807e, 0x01f807e0, 0x1f807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_56[] = { 0xe01f807e, 0x01f807e0, 0x1f807e01, 0xdc0e7038, 0xe1c38707, 0x381ce03f, 0x00fc01e0, 0x07800c00, 0x30000000, };
static const uint32_t profont29_57[] = { 0xe00fc01f, 0x803f007e, 0x00fc01f8, 0x03f007e3, 0x8fc71f8e, 0x3f1c7e7c, 0xfdffffbf, 0xfe3ff83f, 0xe03f8038, };
static const uint32_t profont29_58[] = { 0xe01f807e, 0x01f807f0, 0x3de1e3cf, 0x07f80fc0, 0x1e00fc07, 0xf83cf1e1, 0xef03f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_59[] = { 0xe03f01f8, 0x0fc07e03, 0xf01f80fe, 0x0f78f1ef, 0x07f01f00, 0x7003801c, 0x00e00700, 0x3801c000, };
static const uint32_t profont29_5a[] = { 0xffffffff, 0xffc00700, 0x3c01e00f, 0x007803c0, 0x1e00f007, 0x803c01e0, 0x0f003800, 0xffffffff, 0xffc00000, };
static const uint32_t profont29_5b[] = { 0xfffff8e3, 0x8e38e38e, 0x38e38e38, 0xe38e38e3, 0x8ffffc00, };
static const uint32_t profont29_5c[] = { 0xe001c001, 0xc0038003, 0x80070007, 0x000e000e, 0x001c001c, 0x00380038, 0x00700070, 0x00e000e0, 0x01c001c0, 0x03800380, 0x07000700, 0x0e000e00, 0x1c000000, };
static const uint32_t profont29_5d[] = { 0xffffc71c, 0x71c71c71, 0xc71c71c7, 0x1c71c71c, 0x7ffffc00, };
static const uint32_t profont29_5e[] = { 0x03001e00, 0xfc07f83c, 0xf1e1ef03, 0xd8060000, };
static const uint32_t profont29_5f[] = { 0xffffffff, 0xffff0000, };
static const uint32_t profont29_60[] = { 0x61e1e1e1, 0xe1800000, };
static const uint32_t profont29_61[] = { 0x0ffcfff7, 0xffdc07e0, 0x1f807e01, 0xf807e03f, 0x81f71fdf, 0xf73f9c38, 0x70000000, };
static const uint32_t profont29_62[] = { 0xe003800e, 0x003800e0, 0x03ff0fff, 0x3ffee03b, 0x807e01f8, 0x07e01f80, 0x7e01f80e, 0xfffbffcf, 0xfc000000, };
static const uint32_t profont29_63[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x3800e003, 0x8007001f, 0xff3ffc3f, 0xf0000000, };
static const uint32_t profont29_64[] = { 0x001c0070, 0x01c00700, 0x1c3ff3ff, 0xdfff701f, 0x807e01f8, 0x07e01f80, 0x7e01dc07, 0x7ffcfff0, 0xffc00000, };
static const uint32_t profont29_65[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807fff, 0xffffffff, 0x8007001f, 0xff3ffc3f, 0xf0000000, };
static const uint32_t profont29_66[] = { 0x01e0fc3f, 0x8701c1ff, 0x3fe7fc1c, 0x0380700e, 0x01c03807, 0x00e01c03, 0x80700000, };
static const uint32_t profont29_67[] = { 0x0ffcfff7, 0xffdc07e0, 0x1f807e01, 0xf807e01f, 0x807701df, 0xff3ffc3f, 0xf001c00e, 0x1ff87fc1, 0xfc000000, };
static const uint32_t profont29_68[] = { 0xe003800e, 0x003800e0, 0x03ff0fff, 0x3ffee03b, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01c00000, };
static const uint32_t profont29_69[] = { 0x1c0e0700, 0x0007e3f1, 0xf81c0e07, 0x0381c0e0, 0x7038ffff, 0xffe00000, };
static const uint32_t profont29_6a[] = { 0x07070700, 0x003f3f3f, 0x07070707, 0x07070707, 0x07070707, 0x0efefcf0, };
static const uint32_t profont29_6b[] = { 0xe003800e, 0x003800e0, 0x0381ee0f, 0x3878e3c3, 0x9e0ef03f, 0xc0ff83ef, 0x0f1e383c, 0xe07b80fe, 0x01c00000, };
static const uint32_t profont29_6c[] = { 0xfc7e3f03, 0x81c0e070, 0x381c0e07, 0x0381c0e0, 0x7038ffff, 0xffe00000, };
static const uint32_t profont29_6d[] = { 0xffe1fff3, 0xfff71cee, 0x38fc71f8, 0xe3f1c7e3, 0x8fc71f8e, 0x3f1c7e38, 0xfc71c000, };
static const uint32_t profont29_6e[] = { 0xe1c39fce, 0xffbf8ef8, 0x1fc07e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x70000000, };
static const uint32_t profont29_6f[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e01, 0xf807e01f, 0x8077039f, 0xfe3ff03f, 0x00000000, };
static const uint32_t profont29_70[] = { 0xffc3ffcf, 0xffb80ee0, 0x1f807e01, 0xf807e01f, 0x807e03bf, 0xfefff3ff, 0x0e003800, 0xe003800e, 0x00000000, };
static const uint32_t profont29_71[] = { 0x0ffcfff7, 0xffdc07e0, 0x1f807e01, 0xf807e01f, 0x807701df, 0xff3ffc3f, 0xf001c007, 0x001c0070, 0x01c00000, };
static const uint32_t profont29_72[] = { 0xe1c39fce, 0xffbf8ef8, 0x1fc07e00, 0x3800e003, 0x800e0038, 0x00e00380, 0x00000000, };
static const uint32_t profont29_73[] = { 0x0ffcfff7, 0xfffc00e0, 0x03ff07ff, 0x07fe003c, 0x007003ff, 0xfefff3ff, 0x00000000, };
static const uint32_t profont29_74[] = { 0x1c038070, 0x0e01c1ff, 0x3fe7fc1c, 0x0380700e, 0x01c03807, 0x00700fe0, 0xfc078000, };
static const uint32_t profont29_75[] = { 0xe01f807e, 0x01f807e0, 0x1f807e01, 0xf807e03f, 0x81f71fdf, 0xf73f9c38, 0x70000000, };
static const uint32_t profont29_76[] = { 0xe01f807e, 0x01f807e0, 0x1dc0e703, 0x8e1c3870, 0x7381ce03, 0xf00fc01e, 0x00000000, };
static const uint32_t profont29_77[] = { 0xe38fc71f, 0x8e3f1c7e, 0x38fc71f8, 0xe3f1c7e3, 0x8fc71fdf, 0x7bffe7ef, 0xc38e0000, };
static const uint32_t profont29_78[] = { 0xe01f807f, 0x03de1e3c, 0xf07f80fc, 0x03f01fe0, 0xf3c787bc, 0x0fe01f80, 0x70000000, };
static const uint32_t profont29_79[] = { 0xe01f807e, 0x01f807e0, 0x1f807e01, 0xf807e01f, 0x807701df, 0xff3ffc3f, 0xf001c00e, 0x1ff87fc1, 0xfc000000, };
static const uint32_t profont29_7a[] = { 0xffffffff, 0xfe01e01e, 0x01e01e01, 0xe01e01e0, 0x1e01ffff, 0xfffffc00, };
static const uint32_t profont29_7b[] = { 0x0387c3e3, 0xc1c0e070, 0x381c0e07, 0x0383c7c3, 0x81f03c0e, 0x070381c0, 0xe070381c, 0x0f03e1f0, 0x38000000, };
static const uint32_t profont29_7c[] = { 0xffffffff, 0xffffffff, 0xffe00000, };
static const uint32_t profont29_7d[] = { 0xe07c3e07, 0x81c0e070, 0x381c0e07, 0x0381e07c, 0x0e1f1e0e, 0x070381c0, 0xe070381c, 0x1e3e1f0e, 0x00000000, };
static const uint32_t profont29_7e[] = { 0x3c3bf9ff, 0xffcfee1e, 0x00000000, };
static const uint32_t profont29_82[] = { 0x39ce73bf, 0xcc000000, };
static const uint32_t profont29_83[] = { 0x00780fc0, 0xfe070070, 0x03801c00, 0xe0070038, 0x07f03f81, 0xfc03801c, 0x00e00700, 0x3801c00e, 0x00700380, 0x1c00e007, 0x00703f81, 0xf80f0000, };
static const uint32_t profont29_84[] = { 0x38e71ce3, 0x9c738ef3, 0xfcf30c00, };
static const uint32_t profont29_85[] = { 0xe73f39f9, 0xce000000, };
static const uint32_t profont29_86[] = { 0x1c0e071f, 0xfffffc70, 0x381c0e07, 0x0381c0e0, };
static const uint32_t profont29_87[] = { 0x1c0e071f, 0xfffffc70, 0x38ffffff, 0xe381c0e0, };
static const uint32_t profont29_88[] = { 0x0c0783f1, 0xfef3d860, };
static const uint32_t profont29_89[] = { 0x1ffe7ffd, 0xfffbb8fe, 0x33dc6f38, 0xfc7bf07f, 0xc0ff00fc, 0x0079c3ff, 0xcfffbf7b, 0xfc63d8c7, 0x318c77b8, 0x7fe0ffc0, 0xe7000000, };
static const uint32_t profont29_8a[] = { 0x18c0f781, 0xfc03e007, 0x003f03ff, 0x1ffe703b, 0x807e01f8, 0x007001ff, 0x03ff03fe, 0x0038007e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_8b[] = { 0x31dcee73, 0x9ce39c73, 0x00000000, };
static const uint32_t profont29_8c[] = { 0x0ffcfff7, 0xffddc0e7, 0x039c0e70, 0x39c0e7e3, 0x9f8e7e39, 0xc0e7039c, 0x0e701dc0, 0x7ffcfff0, 0xffc00000, };
static const uint32_t profont29_91[] = { 0x33fdce73, 0x9c000000, };
static const uint32_t profont29_92[] = { 0x39ce73bf, 0xcc000000, };
static const uint32_t profont29_93[] = { 0x30cf3fcf, 0x71ce39c7, 0x38e71c00, };
static const uint32_t profont29_94[] = { 0x38e71ce3, 0x9c738ef3, 0xfcf30c00, };
static const uint32_t profont29_95[] = { 0x0f81ff1f, 0xfcffefff, 0xffffffff, 0xfffffbff, 0x9ffc7fc0, 0xf8000000, };
static const uint32_t profont29_96[] = { 0xffffff00, };
static const uint32_t profont29_97[] = { 0xffffffff, 0xffff0000, };
static const uint32_t profont29_98[] = { 0x3c3bf9ff, 0xffcfee1e, 0x00000000, };
static const uint32_t profont29_99[] = { 0xffcfffff, 0xfff9cff3, 0x9fe739ce, 0x739ce700, };
static const uint32_t profont29_9a[] = { 0x1860f3c1, 0xfe03f007, 0x800c0000, 0x00000ffc, 0xfff7fffc, 0x00e003ff, 0x07ff07fe, 0x003c0070, 0x03fffeff, 0xf3ff0000, };
static const uint32_t profont29_9b[] = { 0x671ce39c, 0xe73bddc6, 0x00000000, };
static const uint32_t profont29_9c[] = { 0x3cf1ffe7, 0xffb9c7e7, 0x1f9c7e7f, 0xf9ffe7ff, 0x9c0e701f, 0xff7ffcf3, 0xf0000000, };
static const uint32_t profont29_9f[] = { 0x38e1c70e, 0x38000000, 0x701f80fc, 0x07e03f01, 0xf80fc07f, 0x07bc78f7, 0x83f80f80, 0x3801c00e, 0x00700380, 0x1c00e000, };
static const uint32_t profont29_a1[] = { 0xff81ffff, 0xffffff80, };
static const uint32_t profont29_a2[] = { 0x07003801, 0xc01f03fe, 0x3ff9dddc, 0xe7e73f38, 0x39c1ce0e, 0x703b81ff, 0xe7ff0ff8, 0x3801c00e, 0x00000000, };
static const uint32_t profont29_a3[] = { 0x0e01fc1f, 0xe0e38e0e, 0x7073801c, 0x00ff07f8, 0x3fc1c00e, 0x00700380, 0x1c00e03f, 0x01f81dff, 0xeffe7fc0, };
static const uint32_t profont29_a4[] = { 0x401701dc, 0x1c7fc1fc, 0x0ee06303, 0xb81fc1ff, 0x1c1dc074, 0x01000000, };
static const uint32_t profont29_a5[] = { 0x600de03d, 0xe0f1e3c1, 0xef0fff9f, 0xff3ffe03, 0x8007000e, 0x03ffe7ff, 0xcfff80e0, 0x01c00380, 0x07000e00, };
static const uint32_t profont29_a6[] = { 0xffffffff, 0x803fffff, 0xffe00000, };
static const uint32_t profont29_a7[] = { 0x0fc0ffc3, 0xff9c0e70, 0x1de073c1, 0xc787ef03, 0x9e0e3c38, 0x78f0f1e1, 0xe3c3c787, 0x0f1c1e70, 0x3df878e0, 0xf381ee03, 0x9c0e7ff0, 0xffc0f800, };
static const uint32_t profont29_a8[] = { 0xe7e7e700, };
static const uint32_t profont29_a9[] = { 0x1c03fe0f, 0xfe307c00, 0x707ce7f3, 0x9fc6e01f, 0x807e01df, 0xc67f387c, 0xe007307c, 0xffe3fe01, 0xc0000000, };
static const uint32_t profont29_aa[] = { 0x0ff3ff7f, 0xf707e07e, 0x07e07707, 0x7ff3ff0f, 0xf000000f, 0xffffffff, };
static const uint32_t profont29_ab[] = { 0x3031c1dc, 0x1ce0ee0e, 0x7073839c, 0x1ce0e383, 0x9c1c7073, 0x03000000, };
static const uint32_t profont29_ac[] = { 0xffffffff, 0xffc00700, 0x1c007001, 0xc0070000, };
static const uint32_t profont29_ad[] = { 0xffffffff, 0xfe000000, };
static const uint32_t profont29_ae[] = { 0x1c03fe0f, 0xfe307c00, 0x73e0efe3, 0xbf86e71f, 0x9c7e71ff, 0x86fe3bf8, 0xeeff39fc, 0xe3c00000, };
static const uint32_t profont29_af[] = { 0xffffff00, };
static const uint32_t profont29_b0[] = { 0x0f03fc7f, 0xe70ee07e, 0x07e07e07, 0x70e7fe3f, 0xc0f00000, };
static const uint32_t profont29_b1[] = { 0x07003801, 0xc00e0070, 0x7fffffff, 0xff070038, 0x01c00e00, 0x707fffff, 0xffff0000, };
static const uint32_t profont29_b2[] = { 0x7a104108, 0x4210fc00, };
static const uint32_t profont29_b3[] = { 0x7a104230, 0x20617800, };
static const uint32_t profont29_b4[] = { 0x0c3cf3cf, 0x0c000000, };
static const uint32_t profont29_b5[] = { 0xe0e3838e, 0x0e3838e0, 0xe3838e0e, 0x3838e0e3, 0x87cfffff, 0xeffe0f80, 0x0e003800, 0xe0038000, };
static const uint32_t profont29_b6[] = { 0x07fc7ff3, 0xffdfc777, 0x1f9c7e71, 0xf9c7e71d, 0xdc77f1cf, 0xff1ffc1f, 0xf071c1c7, 0x071c1c70, 0x71c1c707, 0x1c1c7000, };
static const uint32_t profont29_b7[] = { 0x77fff700, };
static const uint32_t profont29_b8[] = { 0xffffcf7f, 0xef180000, };
static const uint32_t profont29_b9[] = { 0x10e04081, 0x020408fe, };
static const uint32_t profont29_ba[] = { 0x0e07f1ff, 0x38ee0fc1, 0xf83b8e7f, 0xc7f03800, 0x0001ffff, 0xffff0000, };
static const uint32_t profont29_bb[] = { 0x6067071c, 0x1ce0e383, 0x9c1ce0e7, 0x07383b83, 0x9c1dc1c6, 0x06000000, };
static const uint32_t profont29_bc[] = { 0x08007000, 0x20004000, 0x80010002, 0x0084027f, 0x08002000, 0x80020008, 0x00200080, 0x02040818, 0x20508122, 0x04480fe0, 0x01000200, 0x1f000000, };
static const uint32_t profont29_bd[] = { 0x08007000, 0x20004000, 0x80010002, 0x0084027f, 0x08002000, 0x80020008, 0x00200080, 0x023c0884, 0x20088012, 0x00480100, 0x04001000, 0x7e000000, };
static const uint32_t profont29_be[] = { 0x1e004200, 0x04001000, 0xc0004000, 0x4090821e, 0x08002000, 0x80020008, 0x00200080, 0x02040818, 0x20508122, 0x04480fe0, 0x01000200, 0x1f000000, };
static const uint32_t profont29_bf[] = { 0x03800e00, 0x38000000, 0x000e0078, 0x03c01e00, 0xf007803c, 0x00e00380, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_c0[] = { 0x1800f001, 0xe003c007, 0x801e0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c1[] = { 0x006003c0, 0x1e00f007, 0x801e0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c2[] = { 0x03001e00, 0xfc07f81c, 0xe02d0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c3[] = { 0x3c39fcef, 0xffb9fce1, 0xe01e0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c4[] = { 0x3870e1c3, 0x87000000, 0x001e0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c5[] = { 0x07803f01, 0xce06181c, 0xe03f0078, 0x03f00fc0, 0x7381ce0e, 0x1c3871c0, 0xe703b807, 0xffffffff, 0xfff807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_c6[] = { 0x0ffcfff7, 0xffddc0e7, 0x039c0e70, 0x39c0ffe3, 0xff8ffe39, 0xc0e7039c, 0x0e7039c0, 0xe7ff9ffe, 0x7fc00000, };
static const uint32_t profont29_c7[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x3800e003, 0x800e0038, 0x00e00380, 0x7e01dc0e, 0x7ff8ffc0, 0xfc01c00f, 0x007803c0, 0x06000000, };
static const uint32_t profont29_c8[] = { 0x1800f001, 0xe003c007, 0x83ffffff, 0xffffe003, 0x800e0038, 0x00e003ff, 0x8ffe3ff8, 0xe003800e, 0x003800e0, 0x03ffffff, 0xffff0000, };
static const uint32_t profont29_c9[] = { 0x006003c0, 0x1e00f007, 0x83ffffff, 0xffffe003, 0x800e0038, 0x00e003ff, 0x8ffe3ff8, 0xe003800e, 0x003800e0, 0x03ffffff, 0xffff0000, };
static const uint32_t profont29_ca[] = { 0x03001e00, 0xfc07f81c, 0xe3ffffff, 0xffffe003, 0x800e0038, 0x00e003ff, 0x8ffe3ff8, 0xe003800e, 0x003800e0, 0x03ffffff, 0xffff0000, };
static const uint32_t profont29_cb[] = { 0x3870e1c3, 0x87000000, 0x03ffffff, 0xffffe003, 0x800e0038, 0x00e003ff, 0x8ffe3ff8, 0xe003800e, 0x003800e0, 0x03ffffff, 0xffff0000, };
static const uint32_t profont29_cc[] = { 0x1801e007, 0x801e0070, 0x7fffffff, 0xff070038, 0x01c00e00, 0x7003801c, 0x00e00700, 0x3801c00e, 0x00707fff, 0xffffff00, };
static const uint32_t profont29_cd[] = { 0x00c00f00, 0xf00f0070, 0x7fffffff, 0xff070038, 0x01c00e00, 0x7003801c, 0x00e00700, 0x3801c00e, 0x00707fff, 0xffffff00, };
static const uint32_t profont29_ce[] = { 0x02003803, 0xe03f838e, 0x7fffffff, 0xff070038, 0x01c00e00, 0x7003801c, 0x00e00700, 0x3801c00e, 0x00707fff, 0xffffff00, };
static const uint32_t profont29_cf[] = { 0x38e1c70e, 0x38000000, 0x7fffffff, 0xff070038, 0x01c00e00, 0x7003801c, 0x00e00700, 0x3801c00e, 0x00707fff, 0xffffff00, };
static const uint32_t profont29_d0[] = { 0x1fc07fc1, 0xff870e1c, 0x1c7071c1, 0xc707ff9f, 0xfe7ff9c7, 0x071c1c70, 0x71c1c70e, 0x1ff87fc1, 0xfc000000, };
static const uint32_t profont29_d1[] = { 0x3c39fcef, 0xffb9fce1, 0xe3807f01, 0xfe07fc1f, 0xf87ef1f9, 0xe7e3df87, 0xfe0ff81f, 0xe03f807e, 0x01f807e0, 0x1f807e01, 0xf8070000, };
static const uint32_t profont29_d2[] = { 0x0c007800, 0xf001e003, 0x803f03ff, 0x1ffe703b, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_d3[] = { 0x00c00780, 0x3c01e007, 0x003f03ff, 0x1ffe703b, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_d4[] = { 0x03001e00, 0xfc07f83c, 0xf06180fc, 0x0ffc7ff9, 0xc0ee01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_d5[] = { 0x3c39fcef, 0xffb9fce1, 0xe03f03ff, 0x1ffe703b, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_d6[] = { 0x3870e1c3, 0x87000000, 0x003f03ff, 0x1ffe703b, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_d7[] = { 0x601bc0f7, 0x878f3c1f, 0xe03f0078, 0x03f01fe0, 0xf3c787bc, 0x0f601800, };
static const uint32_t profont29_d8[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x3f81fe0f, 0xf87fe3df, 0x9e7ef1ff, 0x87fc1fe0, 0x7f01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_d9[] = { 0x1800f001, 0xe003c007, 0x838c7e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_da[] = { 0x006003c0, 0x1e00f007, 0x838c7e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_db[] = { 0x03001e00, 0xfc07f83c, 0xf0618e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_dc[] = { 0x3870e1c3, 0x87000000, 0x03807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f807e, 0x01f80770, 0x39ffe3ff, 0x03f00000, };
static const uint32_t profont29_dd[] = { 0x00600780, 0x78078078, 0x719f80fc, 0x07e03f01, 0xf80fc07f, 0x07bc78f7, 0x83f80f80, 0x3801c00e, 0x00700380, 0x1c00e000, };
static const uint32_t profont29_de[] = { 0xe003800e, 0x003ff0ff, 0xf3ffee03, 0xb807e01f, 0x807e03bf, 0xfefff3ff, 0x0e003800, 0xe003800e, 0x00000000, };
static const uint32_t profont29_df[] = { 0x03c03f03, 0xfc3cf3c3, 0xbc1fc0fc, 0x07e07707, 0x3839c1ce, 0x0e703b80, 0xfc07e03f, 0x01f81fc7, 0xee3e71e3, 0x801c00e0, 0x00000000, };
static const uint32_t profont29_e0[] = { 0x06003c00, 0x7800f001, 0xe0030000, 0x00000ffc, 0xfff7ffdc, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_e1[] = { 0x006003c0, 0x1e00f007, 0x800c0000, 0x00000ffc, 0xfff7ffdc, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_e2[] = { 0x03001e00, 0xfc07f83c, 0xf0618000, 0x00000ffc, 0xfff7ffdc, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_e3[] = { 0x3c39fcef, 0xffb9fce1, 0xe0000000, 0x03ff3ffd, 0xfff701f8, 0x07e01f80, 0x7e01f80f, 0xe07dc7f7, 0xfdcfe70e, 0x1c000000, };
static const uint32_t profont29_e4[] = { 0x3870e1c3, 0x87000000, 0x003ff3ff, 0xdfff701f, 0x807e01f8, 0x07e01f80, 0xfe07dc7f, 0x7fdcfe70, 0xe1c00000, };
static const uint32_t profont29_e5[] = { 0x07c03f80, 0xc603180c, 0x603f807c, 0x03ff3ffd, 0xfff701f8, 0x07e01f80, 0x7e01f80f, 0xe07dc7f7, 0xfdcfe70e, 0x1c000000, };
static const uint32_t profont29_e6[] = { 0x0fc0ffc7, 0xff9ddee7, 0x3f9c7e7f, 0xf9ffe7ff, 0x9c07701f, 0xff3ffc3f, 0xf0000000, };
static const uint32_t profont29_e7[] = { 0x0fc0ffc7, 0xff9c0ee0, 0x1f807e00, 0x3800e003, 0x8007001f, 0xff3ffc3f, 0xf07003c0, 0x1e00f001, 0x80000000, };
static const uint32_t profont29_e8[] = { 0x1800f001, 0xe003c007, 0x800c0000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7fffffff, 0xffff8007, 0x001fff3f, 0xfc3ff000, };
static const uint32_t profont29_e9[] = { 0x006003c0, 0x1e00f007, 0x800c0000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7fffffff, 0xffff8007, 0x001fff3f, 0xfc3ff000, };
static const uint32_t profont29_ea[] = { 0x03001e00, 0xfc07f83c, 0xf0618000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7fffffff, 0xffff8007, 0x001fff3f, 0xfc3ff000, };
static const uint32_t profont29_eb[] = { 0x3870e1c3, 0x87000000, 0x003f03ff, 0x1ffe703b, 0x807e01ff, 0xffffffff, 0xfe001c00, 0x7ffcfff0, 0xffc00000, };
static const uint32_t profont29_ec[] = { 0x60781e07, 0x81e06000, 0x00fc7e3f, 0x0381c0e0, 0x70381c0e, 0x071fffff, 0xfc000000, };
static const uint32_t profont29_ed[] = { 0x0303c3c3, 0xc3c0c000, 0x00fc7e3f, 0x0381c0e0, 0x70381c0e, 0x071fffff, 0xfc000000, };
static const uint32_t profont29_ee[] = { 0x0c0783f1, 0xfef3d860, 0x0000fc3f, 0x0fc0701c, 0x0701c070, 0x1c0701c3, 0xfeffbfe0, };
static const uint32_t profont29_ef[] = { 0xe3f1f8e0, 0x0007e3f1, 0xf81c0e07, 0x0381c0e0, 0x7038ffff, 0xffe00000, };
static const uint32_t profont29_f0[] = { 0x3181ef03, 0xf807c01f, 0x00fe07bc, 0x0c7800f0, 0x3fe3ffdf, 0xff703f80, 0x7e01f807, 0xe01f807e, 0x01dc0e7f, 0xf8ffc0fc, 0x00000000, };
static const uint32_t profont29_f1[] = { 0x3c39fcef, 0xffb9fce1, 0xe0000000, 0x3870e7f3, 0xbfefe3be, 0x07f01f80, 0x7e01f807, 0xe01f807e, 0x01f807e0, 0x1c000000, };
static const uint32_t profont29_f2[] = { 0x1800f001, 0xe003c007, 0x800c0000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7e01f807, 0xe01f8077, 0x039ffe3f, 0xf03f0000, };
static const uint32_t profont29_f3[] = { 0x006003c0, 0x1e00f007, 0x800c0000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7e01f807, 0xe01f8077, 0x039ffe3f, 0xf03f0000, };
static const uint32_t profont29_f4[] = { 0x03001e00, 0xfc07f83c, 0xf0618000, 0x00000fc0, 0xffc7ff9c, 0x0ee01f80, 0x7e01f807, 0xe01f8077, 0x039ffe3f, 0xf03f0000, };
static const uint32_t profont29_f5[] = { 0x3c39fcef, 0xffb9fce1, 0xe0000000, 0x03f03ff1, 0xffe703b8, 0x07e01f80, 0x7e01f807, 0xe01dc0e7, 0xff8ffc0f, 0xc0000000, };
static const uint32_t profont29_f6[] = { 0x3870e1c3, 0x87000000, 0x003f03ff, 0x1ffe703b, 0x807e01f8, 0x07e01f80, 0x7e01dc0e, 0x7ff8ffc0, 0xfc000000, };
static const uint32_t profont29_f7[] = { 0x07003801, 0xc0000000, 0x7fffffff, 0xff000000, 0x00000e00, 0x70038000, };
static const uint32_t profont29_f8[] = { 0x0fc0ffc7, 0xff9c1ee0, 0xff877e39, 0xf9c7ee1f, 0xf077839f, 0xfe3ff03f, 0x00000000, };
static const uint32_t profont29_f9[] = { 0x1800f001, 0xe003c007, 0x800c0000, 0x0000e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_fa[] = { 0x006003c0, 0x1e00f007, 0x800c0000, 0x0000e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_fb[] = { 0x03001e00, 0xfc07f83c, 0xf0618000, 0x0000e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe03f81f7, 0x1fdff73f, 0x9c387000, };
static const uint32_t profont29_fc[] = { 0x3870e1c3, 0x87000000, 0x03807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0xfe07dc7f, 0x7fdcfe70, 0xe1c00000, };
static const uint32_t profont29_fd[] = { 0x006003c0, 0x1e00f007, 0x800c0000, 0x0000e01f, 0x807e01f8, 0x07e01f80, 0x7e01f807, 0xe01f8077, 0x01dfff3f, 0xfc3ff001, 0xc00e1ff8, 0x7fc1fc00, };
static const uint32_t profont29_fe[] = { 0xe003800e, 0x003800e0, 0x03ff0fff, 0x3ffee03b, 0x807e01f8, 0x07e01f80, 0x7e01f80e, 0xfffbffcf, 0xfc3800e0, 0x03800e00, 0x38000000, };
static const uint32_t profont29_ff[] = { 0x3870e1c3, 0x87000000, 0x03807e01, 0xf807e01f, 0x807e01f8, 0x07e01f80, 0x7e01dc07, 0x7ffcfff1, 0xffc00700, 0x387fe1ff, 0x07f80000, };
static const uint32_t profont29_null[] = { 0 };

const struct font profont29 = {
	.ascent = 24,
	.descent = -5,
	.glyphs = {
		   {0, 0, 0, 0, 16, profont29_null},	// 0x00
		   {0, 0, 0, 0, 16, profont29_null},	// 0x01
		   {0, 0, 0, 0, 16, profont29_null},	// 0x02
		   {0, 0, 0, 0, 16, profont29_null},	// 0x03
		   {0, 0, 0, 0, 16, profont29_null},	// 0x04
		   {0, 0, 0, 0, 16, profont29_null},	// 0x05
		   {0, 0, 0, 0, 16, profont29_null},	// 0x06
		   {0, 0, 0, 0, 16, profont29_null},	// 0x07
		   {0, 0, 0, 0, 16, profont29_null},	// 0x08
		   {0, 0, 0, 0, 16, profont29_null},	// 0x09
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0a
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0b
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0c
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0d
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0e
		   {0, 0, 0, 0, 16, profont29_null},	// 0x0f
		   {0, 0, 0, 0, 16, profont29_null},	// 0x10
		   {0, 0, 0, 0, 16, profont29_null},	// 0x11
		   {0, 0, 0, 0, 16, profont29_null},	// 0x12
		   {0, 0, 0, 0, 16, profont29_null},	// 0x13
		   {0, 0, 0, 0, 16, profont29_null},	// 0x14
		   {0, 0, 0, 0, 16, profont29_null},	// 0x15
		   {0, 0, 0, 0, 16, profont29_null},	// 0x16
		   {0, 0, 0, 0, 16, profont29_null},	// 0x17
		   {0, 0, 0, 0, 16, profont29_null},	// 0x18
		   {0, 0, 0, 0, 16, profont29_null},	// 0x19
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1a
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1b
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1c
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1d
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1e
		   {0, 0, 0, 0, 16, profont29_null},	// 0x1f
		   {0, 0, 0, 0, 16, profont29_null},	// 0x20
		   {3, 19, 5, 0, 16, profont29_21},	// 0x21
		   {9, 9, 2, 13, 16, profont29_22},	// 0x22
		   {15, 15, 0, 5, 16, profont29_23},	// 0x23
		   {13, 25, 0, -3, 16, profont29_24},	// 0x24
		   {14, 19, 0, 0, 16, profont29_25},	// 0x25
		   {14, 19, 0, 0, 16, profont29_26},	// 0x26
		   {3, 9, 5, 13, 16, profont29_27},	// 0x27
		   {9, 25, 3, -3, 16, profont29_28},	// 0x28
		   {9, 25, 2, -3, 16, profont29_29},	// 0x29
		   {13, 13, 0, 5, 16, profont29_2a},	// 0x2a
		   {13, 13, 0, 3, 16, profont29_2b},	// 0x2b
		   {6, 11, 3, -5, 16, profont29_2c},	// 0x2c
		   {8, 3, 3, 8, 16, profont29_2d},	// 0x2d
		   {5, 5, 4, 1, 16, profont29_2e},	// 0x2e
		   {15, 26, 0, -5, 16, profont29_2f},	// 0x2f
		   {14, 19, 0, 0, 16, profont29_30},	// 0x30
		   {13, 19, 0, 0, 16, profont29_31},	// 0x31
		   {14, 19, 0, 0, 16, profont29_32},	// 0x32
		   {14, 19, 0, 0, 16, profont29_33},	// 0x33
		   {14, 19, 0, 0, 16, profont29_34},	// 0x34
		   {14, 19, 0, 0, 16, profont29_35},	// 0x35
		   {14, 19, 0, 0, 16, profont29_36},	// 0x36
		   {14, 19, 0, 0, 16, profont29_37},	// 0x37
		   {14, 19, 0, 0, 16, profont29_38},	// 0x38
		   {14, 19, 0, 0, 16, profont29_39},	// 0x39
		   {5, 13, 4, 1, 16, profont29_3a},	// 0x3a
		   {6, 19, 3, -5, 16, profont29_3b},	// 0x3b
		   {12, 19, 2, 0, 16, profont29_3c},	// 0x3c
		   {14, 9, 0, 5, 16, profont29_3d},	// 0x3d
		   {12, 19, 2, 0, 16, profont29_3e},	// 0x3e
		   {14, 19, 0, 0, 16, profont29_3f},	// 0x3f
		   {14, 19, 0, 0, 16, profont29_40},	// 0x40
		   {14, 19, 0, 0, 16, profont29_41},	// 0x41
		   {14, 19, 0, 0, 16, profont29_42},	// 0x42
		   {14, 19, 0, 0, 16, profont29_43},	// 0x43
		   {14, 19, 0, 0, 16, profont29_44},	// 0x44
		   {14, 19, 0, 0, 16, profont29_45},	// 0x45
		   {14, 19, 0, 0, 16, profont29_46},	// 0x46
		   {14, 19, 0, 0, 16, profont29_47},	// 0x47
		   {14, 19, 0, 0, 16, profont29_48},	// 0x48
		   {13, 19, 0, 0, 16, profont29_49},	// 0x49
		   {14, 19, 0, 0, 16, profont29_4a},	// 0x4a
		   {13, 19, 0, 0, 16, profont29_4b},	// 0x4b
		   {14, 19, 0, 0, 16, profont29_4c},	// 0x4c
		   {15, 19, 0, 0, 16, profont29_4d},	// 0x4d
		   {14, 19, 0, 0, 16, profont29_4e},	// 0x4e
		   {14, 19, 0, 0, 16, profont29_4f},	// 0x4f
		   {14, 19, 0, 0, 16, profont29_50},	// 0x50
		   {14, 22, 0, -3, 16, profont29_51},	// 0x51
		   {14, 19, 0, 0, 16, profont29_52},	// 0x52
		   {14, 19, 0, 0, 16, profont29_53},	// 0x53
		   {13, 19, 0, 0, 16, profont29_54},	// 0x54
		   {14, 19, 0, 0, 16, profont29_55},	// 0x55
		   {14, 19, 0, 0, 16, profont29_56},	// 0x56
		   {15, 19, 0, 0, 16, profont29_57},	// 0x57
		   {14, 19, 0, 0, 16, profont29_58},	// 0x58
		   {13, 19, 0, 0, 16, profont29_59},	// 0x59
		   {14, 19, 0, 0, 16, profont29_5a},	// 0x5a
		   {6, 25, 5, -3, 16, profont29_5b},	// 0x5b
		   {15, 26, 1, -5, 16, profont29_5c},	// 0x5c
		   {6, 25, 2, -3, 16, profont29_5d},	// 0x5d
		   {14, 8, 0, 11, 16, profont29_5e},	// 0x5e
		   {16, 3, 0, -5, 16, profont29_5f},	// 0x5f
		   {7, 6, 2, 15, 16, profont29_60},	// 0x60
		   {14, 14, 0, 0, 16, profont29_61},	// 0x61
		   {14, 19, 0, 0, 16, profont29_62},	// 0x62
		   {14, 14, 0, 0, 16, profont29_63},	// 0x63
		   {14, 19, 0, 0, 16, profont29_64},	// 0x64
		   {14, 14, 0, 0, 16, profont29_65},	// 0x65
		   {11, 19, 2, 0, 16, profont29_66},	// 0x66
		   {14, 19, 0, -5, 16, profont29_67},	// 0x67
		   {14, 19, 0, 0, 16, profont29_68},	// 0x68
		   {9, 19, 2, 0, 16, profont29_69},	// 0x69
		   {8, 24, 0, -5, 16, profont29_6a},	// 0x6a
		   {14, 19, 0, 0, 16, profont29_6b},	// 0x6b
		   {9, 19, 2, 0, 16, profont29_6c},	// 0x6c
		   {15, 14, 0, 0, 16, profont29_6d},	// 0x6d
		   {14, 14, 0, 0, 16, profont29_6e},	// 0x6e
		   {14, 14, 0, 0, 16, profont29_6f},	// 0x6f
		   {14, 19, 0, -5, 16, profont29_70},	// 0x70
		   {14, 19, 0, -5, 16, profont29_71},	// 0x71
		   {14, 14, 0, 0, 16, profont29_72},	// 0x72
		   {14, 14, 0, 0, 16, profont29_73},	// 0x73
		   {11, 19, 2, 0, 16, profont29_74},	// 0x74
		   {14, 14, 0, 0, 16, profont29_75},	// 0x75
		   {14, 14, 0, 0, 16, profont29_76},	// 0x76
		   {15, 14, 0, 0, 16, profont29_77},	// 0x77
		   {14, 14, 0, 0, 16, profont29_78},	// 0x78
		   {14, 19, 0, -5, 16, profont29_79},	// 0x79
		   {13, 14, 0, 0, 16, profont29_7a},	// 0x7a
		   {9, 29, 3, -5, 16, profont29_7b},	// 0x7b
		   {3, 25, 5, -3, 16, profont29_7c},	// 0x7c
		   {9, 29, 2, -5, 16, profont29_7d},	// 0x7d
		   {13, 5, 0, 8, 16, profont29_7e},	// 0x7e
		   {0, 0, 0, 0, 16, profont29_null},	// 0x7f
		   {0, 0, 0, 0, 16, profont29_null},	// 0x80
		   {0, 0, 0, 0, 16, profont29_null},	// 0x81
		   {5, 8, 0, -3, 16, profont29_82},	// 0x82
		   {13, 29, 0, -5, 16, profont29_83},	// 0x83
		   {11, 8, 0, -3, 16, profont29_84},	// 0x84
		   {13, 3, 0, 0, 16, profont29_85},	// 0x85
		   {9, 14, 2, 5, 16, profont29_86},	// 0x86
		   {9, 14, 2, 5, 16, profont29_87},	// 0x87
		   {10, 6, 2, 16, 16, profont29_88},	// 0x88
		   {15, 22, 0, 0, 16, profont29_89},	// 0x89
		   {14, 24, 0, 0, 16, profont29_8a},	// 0x8a
		   {5, 13, 0, -1, 16, profont29_8b},	// 0x8b
		   {14, 19, 0, 0, 16, profont29_8c},	// 0x8c
		   {0, 0, 0, 0, 16, profont29_null},	// 0x8d
		   {0, 0, 0, 0, 16, profont29_null},	// 0x8e
		   {0, 0, 0, 0, 16, profont29_null},	// 0x8f
		   {0, 0, 0, 0, 16, profont29_null},	// 0x90
		   {5, 8, 5, 11, 16, profont29_91},	// 0x91
		   {5, 8, 6, 11, 16, profont29_92},	// 0x92
		   {11, 8, 2, 11, 16, profont29_93},	// 0x93
		   {11, 8, 3, 11, 16, profont29_94},	// 0x94
		   {13, 13, 0, 3, 16, profont29_95},	// 0x95
		   {8, 3, 3, 8, 16, profont29_96},	// 0x96
		   {16, 3, 0, 8, 16, profont29_97},	// 0x97
		   {13, 5, 0, 16, 16, profont29_98},	// 0x98
		   {15, 8, 0, 11, 16, profont29_99},	// 0x99
		   {14, 22, 0, 0, 16, profont29_9a},	// 0x9a
		   {5, 13, 0, -1, 16, profont29_9b},	// 0x9b
		   {14, 14, 0, 0, 16, profont29_9c},	// 0x9c
		   {0, 0, 0, 0, 16, profont29_null},	// 0x9d
		   {0, 0, 0, 0, 16, profont29_null},	// 0x9e
		   {13, 24, 0, 0, 16, profont29_9f},	// 0x9f
		   {0, 0, 0, 0, 16, profont29_null},	// 0xa0
		   {3, 19, 8, 0, 16, profont29_a1},	// 0xa1
		   {13, 20, 0, -3, 16, profont29_a2},	// 0xa2
		   {13, 22, 0, 0, 16, profont29_a3},	// 0xa3
		   {13, 13, 0, 0, 16, profont29_a4},	// 0xa4
		   {15, 19, 0, 0, 16, profont29_a5},	// 0xa5
		   {3, 25, 5, -3, 16, profont29_a6},	// 0xa6
		   {14, 27, 0, -3, 16, profont29_a7},	// 0xa7
		   {8, 3, 3, 16, 16, profont29_a8},	// 0xa8
		   {14, 19, 0, 0, 16, profont29_a9},	// 0xa9
		   {12, 16, 2, 8, 16, profont29_aa},	// 0xaa
		   {13, 13, 0, -1, 16, profont29_ab},	// 0xab
		   {14, 8, 0, 3, 16, profont29_ac},	// 0xac
		   {13, 3, 0, 8, 16, profont29_ad},	// 0xad
		   {14, 17, 0, 2, 16, profont29_ae},	// 0xae
		   {8, 3, 3, 16, 16, profont29_af},	// 0xaf
		   {12, 12, 2, 10, 16, profont29_b0},	// 0xb0
		   {13, 16, 0, 0, 16, profont29_b1},	// 0xb1
		   {6, 9, 4, 15, 16, profont29_b2},	// 0xb2
		   {6, 9, 4, 15, 16, profont29_b3},	// 0xb3
		   {7, 6, 5, 16, 16, profont29_b4},	// 0xb4
		   {14, 18, 0, -5, 16, profont29_b5},	// 0xb5
		   {14, 22, 0, 0, 16, profont29_b6},	// 0xb6
		   {5, 5, 5, 6, 16, profont29_b7},	// 0xb7
		   {6, 8, 3, -5, 16, profont29_b8},	// 0xb8
		   {7, 9, 4, 15, 16, profont29_b9},	// 0xb9
		   {11, 16, 3, 8, 16, profont29_ba},	// 0xba
		   {13, 13, 0, -1, 16, profont29_bb},	// 0xbb
		   {15, 24, 0, 0, 16, profont29_bc},	// 0xbc
		   {15, 24, 0, 0, 16, profont29_bd},	// 0xbd
		   {15, 24, 0, 0, 16, profont29_be},	// 0xbe
		   {14, 19, 0, 0, 16, profont29_bf},	// 0xbf
		   {14, 24, 0, 0, 16, profont29_c0},	// 0xc0
		   {14, 24, 0, 0, 16, profont29_c1},	// 0xc1
		   {14, 24, 0, 0, 16, profont29_c2},	// 0xc2
		   {14, 24, 0, 0, 16, profont29_c3},	// 0xc3
		   {14, 24, 0, 0, 16, profont29_c4},	// 0xc4
		   {14, 24, 0, 0, 16, profont29_c5},	// 0xc5
		   {14, 19, 0, 0, 16, profont29_c6},	// 0xc6
		   {14, 24, 0, -5, 16, profont29_c7},	// 0xc7
		   {14, 24, 0, 0, 16, profont29_c8},	// 0xc8
		   {14, 24, 0, 0, 16, profont29_c9},	// 0xc9
		   {14, 24, 0, 0, 16, profont29_ca},	// 0xca
		   {14, 24, 0, 0, 16, profont29_cb},	// 0xcb
		   {13, 24, 0, 0, 16, profont29_cc},	// 0xcc
		   {13, 24, 0, 0, 16, profont29_cd},	// 0xcd
		   {13, 24, 0, 0, 16, profont29_ce},	// 0xce
		   {13, 24, 0, 0, 16, profont29_cf},	// 0xcf
		   {14, 19, 0, 0, 16, profont29_d0},	// 0xd0
		   {14, 24, 0, 0, 16, profont29_d1},	// 0xd1
		   {14, 24, 0, 0, 16, profont29_d2},	// 0xd2
		   {14, 24, 0, 0, 16, profont29_d3},	// 0xd3
		   {14, 24, 0, 0, 16, profont29_d4},	// 0xd4
		   {14, 24, 0, 0, 16, profont29_d5},	// 0xd5
		   {14, 24, 0, 0, 16, profont29_d6},	// 0xd6
		   {14, 13, 0, 3, 16, profont29_d7},	// 0xd7
		   {14, 19, 0, 0, 16, profont29_d8},	// 0xd8
		   {14, 24, 0, 0, 16, profont29_d9},	// 0xd9
		   {14, 24, 0, 0, 16, profont29_da},	// 0xda
		   {14, 24, 0, 0, 16, profont29_db},	// 0xdb
		   {14, 24, 0, 0, 16, profont29_dc},	// 0xdc
		   {13, 24, 0, 0, 16, profont29_dd},	// 0xdd
		   {14, 19, 0, 0, 16, profont29_de},	// 0xde
		   {13, 25, 0, -3, 16, profont29_df},	// 0xdf
		   {14, 22, 0, 0, 16, profont29_e0},	// 0xe0
		   {14, 22, 0, 0, 16, profont29_e1},	// 0xe1
		   {14, 22, 0, 0, 16, profont29_e2},	// 0xe2
		   {14, 21, 0, 0, 16, profont29_e3},	// 0xe3
		   {14, 19, 0, 0, 16, profont29_e4},	// 0xe4
		   {14, 21, 0, 0, 16, profont29_e5},	// 0xe5
		   {14, 14, 0, 0, 16, profont29_e6},	// 0xe6
		   {14, 19, 0, -5, 16, profont29_e7},	// 0xe7
		   {14, 22, 0, 0, 16, profont29_e8},	// 0xe8
		   {14, 22, 0, 0, 16, profont29_e9},	// 0xe9
		   {14, 22, 0, 0, 16, profont29_ea},	// 0xea
		   {14, 19, 0, 0, 16, profont29_eb},	// 0xeb
		   {9, 22, 2, 0, 16, profont29_ec},	// 0xec
		   {9, 22, 2, 0, 16, profont29_ed},	// 0xed
		   {10, 22, 2, 0, 16, profont29_ee},	// 0xee
		   {9, 19, 2, 0, 16, profont29_ef},	// 0xef
		   {14, 23, 0, 0, 16, profont29_f0},	// 0xf0
		   {14, 21, 0, 0, 16, profont29_f1},	// 0xf1
		   {14, 22, 0, 0, 16, profont29_f2},	// 0xf2
		   {14, 22, 0, 0, 16, profont29_f3},	// 0xf3
		   {14, 22, 0, 0, 16, profont29_f4},	// 0xf4
		   {14, 21, 0, 0, 16, profont29_f5},	// 0xf5
		   {14, 19, 0, 0, 16, profont29_f6},	// 0xf6
		   {13, 14, 0, 2, 16, profont29_f7},	// 0xf7
		   {14, 14, 0, 0, 16, profont29_f8},	// 0xf8
		   {14, 22, 0, 0, 16, profont29_f9},	// 0xf9
		   {14, 22, 0, 0, 16, profont29_fa},	// 0xfa
		   {14, 22, 0, 0, 16, profont29_fb},	// 0xfb
		   {14, 19, 0, 0, 16, profont29_fc},	// 0xfc
		   {14, 27, 0, -5, 16, profont29_fd},	// 0xfd
		   {14, 24, 0, -5, 16, profont29_fe},	// 0xfe
		   {14, 24, 0, -5, 16, profont29_ff},	// 0xff
		   },
};
