// generated by: ./bdf2ggm -i profont22.bdf (don't edit)
// Copyright: "ProFont Distribution 2.2 Ñ Generated by Fontographer 4.1.5"
#include "lcd.h"
static const uint32_t profont22_21[] = { 0xfffff0f0, };
static const uint32_t profont22_22[] = { 0xcf3cf3cf, 0x30000000, };
static const uint32_t profont22_23[] = { 0x330ccfff, 0xff330ccf, 0xffff330c, 0xc0000000, };
static const uint32_t profont22_24[] = { 0x0c0303f1, 0xfeedf33c, 0xc3b07f0f, 0xe0dc33cc, 0xfb77f8fc, 0x0c030000, };
static const uint32_t profont22_25[] = { 0x3fdffccf, 0x37cfb3c7, 0xf0fe3cdf, 0x3ecf33c7, 0xb0c00000, };
static const uint32_t profont22_26[] = { 0x3e1fce33, 0x1cce3f07, 0x81e0fcf3, 0xfc7b9e7f, 0xcf300000, };
static const uint32_t profont22_27[] = { 0xfff00000, };
static const uint32_t profont22_28[] = { 0x0c739ce3, 0x0c30c30c, 0x30c3870e, 0x1c300000, };
static const uint32_t profont22_29[] = { 0xc3870e1c, 0x30c30c30, 0xc30c739c, 0xe3000000, };
static const uint32_t profont22_2a[] = { 0x0c030ccf, 0xff3f0fcf, 0xff330c03, 0x00000000, };
static const uint32_t profont22_2b[] = { 0x0c0300c0, 0x30fffff0, 0xc0300c03, 0x00000000, };
static const uint32_t profont22_2c[] = { 0x33de719d, 0xdc400000, };
static const uint32_t profont22_2d[] = { 0xfff00000, };
static const uint32_t profont22_2e[] = { 0x6ff60000, };
static const uint32_t profont22_2f[] = { 0x00600c03, 0x00601803, 0x00c01806, 0x00c03006, 0x0180300c, 0x0180600c, 0x03006000, };
static const uint32_t profont22_30[] = { 0x3f1fee1f, 0x07c3f1fc, 0xef73f8fc, 0x3e0f877f, 0x8fc00000, };
static const uint32_t profont22_31[] = { 0x0c0307c1, 0xf00c0300, 0xc0300c03, 0x00c030ff, 0xfff00000, };
static const uint32_t profont22_32[] = { 0x3f1fee1f, 0x0300c070, 0x381c0e07, 0x0381c0ff, 0xfff00000, };
static const uint32_t profont22_33[] = { 0x3f1fee1f, 0x0300c060, 0xf03e01c0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_34[] = { 0x0301c0f0, 0x7c3b1cce, 0x330cffff, 0xf0300c0f, 0xc3f00000, };
static const uint32_t profont22_35[] = { 0xfffffc03, 0x00ff3fe0, 0x1c0300c0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_36[] = { 0x3f1fce03, 0x00ff3fec, 0x1f03c0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_37[] = { 0xfffff00c, 0x0300c070, 0x381c0e03, 0x00c0300c, 0x03000000, };
static const uint32_t profont22_38[] = { 0x3f1fee1f, 0x03c0d863, 0xf1fee1f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_39[] = { 0x3f1fee1f, 0x03c0f03c, 0x0f837fcf, 0xf00c073f, 0x8fc00000, };
static const uint32_t profont22_3a[] = { 0x6ff6006f, 0xf6000000, };
static const uint32_t profont22_3b[] = { 0x33de6000, 0xcf79c677, 0x71000000, };
static const uint32_t profont22_3c[] = { 0x03070e1c, 0x3870e0e0, 0x70381c0e, 0x07030000, };
static const uint32_t profont22_3d[] = { 0xfffff000, 0x00fffff0, };
static const uint32_t profont22_3e[] = { 0xc0e07038, 0x1c0e0707, 0x0e1c3870, 0xe0c00000, };
static const uint32_t profont22_3f[] = { 0x3f1fee1f, 0x0300c070, 0x381c0e03, 0x0000000c, 0x03000000, };
static const uint32_t profont22_40[] = { 0x3f1fee1f, 0x03c7f3fc, 0xcf33cff1, 0xec03807f, 0xcff00000, };
static const uint32_t profont22_41[] = { 0x0c0781e0, 0xcc331866, 0x1b03ffff, 0xfc0f03c0, 0xf0300000, };
static const uint32_t profont22_42[] = { 0xff3fec1f, 0x03c0f06f, 0xf3fec1f0, 0x3c0f07ff, 0xbfc00000, };
static const uint32_t profont22_43[] = { 0x3f1fee1f, 0x03c0300c, 0x0300c030, 0x0c0f877f, 0x8fc00000, };
static const uint32_t profont22_44[] = { 0xff3fec1f, 0x03c0f03c, 0x0f03c0f0, 0x3c0f07ff, 0xbfc00000, };
static const uint32_t profont22_45[] = { 0xfffffc03, 0x00c0300f, 0xf3fcc030, 0x0c0300ff, 0xfff00000, };
static const uint32_t profont22_46[] = { 0xfffffc03, 0x00c0300f, 0xf3fcc030, 0x0c0300c0, 0x30000000, };
static const uint32_t profont22_47[] = { 0x3f1fee1f, 0x03c0300c, 0x3f0fc0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_48[] = { 0xc0f03c0f, 0x03c0f03f, 0xffffc0f0, 0x3c0f03c0, 0xf0300000, };
static const uint32_t profont22_49[] = { 0xfffff0c0, 0x300c0300, 0xc0300c03, 0x00c030ff, 0xfff00000, };
static const uint32_t profont22_4a[] = { 0x00c0300c, 0x0300c030, 0x0c03c0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_4b[] = { 0xc1f0ec73, 0x38dc3e0f, 0x03e0dc33, 0x8c730ec1, 0xf0300000, };
static const uint32_t profont22_4c[] = { 0xc0300c03, 0x00c0300c, 0x0300c030, 0x0c0300ff, 0xfff00000, };
static const uint32_t profont22_4d[] = { 0xc0f87f3f, 0xffdef33c, 0xcf33c0f0, 0x3c0f03c0, 0xf0300000, };
static const uint32_t profont22_4e[] = { 0xc0f83f0f, 0xe3dcf3bc, 0x7f0fc1f0, 0x3c0f03c0, 0xf0300000, };
static const uint32_t profont22_4f[] = { 0x3f1fee1f, 0x03c0f03c, 0x0f03c0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_50[] = { 0xff3fec1f, 0x03c0f07f, 0xfbfcc030, 0x0c0300c0, 0x30000000, };
static const uint32_t profont22_51[] = { 0x3f1fee1f, 0x03c0f03c, 0x0f03c0f0, 0x3ccfbf7f, 0x8fe01c03, };
static const uint32_t profont22_52[] = { 0xff3fec1f, 0x03c0f06f, 0xf3fec1f0, 0x3c0f03c0, 0xf0300000, };
static const uint32_t profont22_53[] = { 0x3f1fee1f, 0x03c03807, 0xf0fe01c0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_54[] = { 0xfffff0c0, 0x300c0300, 0xc0300c03, 0x00c0300c, 0x03000000, };
static const uint32_t profont22_55[] = { 0xc0f03c0f, 0x03c0f03c, 0x0f03c0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_56[] = { 0xc0f03c0f, 0x03c0f036, 0x1986330c, 0xc1e0780c, 0x03000000, };
static const uint32_t profont22_57[] = { 0xc0f03c0f, 0x03c0f03c, 0xcf33ccf7, 0xbfffcfe1, 0xf0300000, };
static const uint32_t profont22_58[] = { 0xc0f03c0f, 0x87738fc1, 0xe0783f1c, 0xee1f03c0, 0xf0300000, };
static const uint32_t profont22_59[] = { 0xc0f03c0f, 0x03c0f877, 0x38fc1e03, 0x00c0300c, 0x03000000, };
static const uint32_t profont22_5a[] = { 0xfffff00c, 0x070381c0, 0xe070381c, 0x0e0300ff, 0xfff00000, };
static const uint32_t profont22_5b[] = { 0xffcccccc, 0xcccccccc, 0xff000000, };
static const uint32_t profont22_5c[] = { 0xc0180180, 0x30030060, 0x0600c00c, 0x01801803, 0x00300600, 0x600c00c0, 0x18018030, };
static const uint32_t profont22_5d[] = { 0xff333333, 0x33333333, 0xff000000, };
static const uint32_t profont22_5e[] = { 0x0c0783f1, 0xcee1d020, };
static const uint32_t profont22_5f[] = { 0xffffff00, };
static const uint32_t profont22_60[] = { 0xce730000, };
static const uint32_t profont22_61[] = { 0x3fdffe0f, 0x03c0f07c, 0x3f9f7ecf, 0x30000000, };
static const uint32_t profont22_62[] = { 0xc0300c03, 0x00ff3fec, 0x1f03c0f0, 0x3c0f07ff, 0xbfc00000, };
static const uint32_t profont22_63[] = { 0x3f1fee1f, 0x03c0300c, 0x03807fcf, 0xf0000000, };
static const uint32_t profont22_64[] = { 0x00c0300c, 0x033fdffe, 0x0f03c0f0, 0x3c0f837f, 0xcff00000, };
static const uint32_t profont22_65[] = { 0x3f1fee1f, 0x03fffffc, 0x03807fcf, 0xf0000000, };
static const uint32_t profont22_66[] = { 0x0f1f3830, 0xfcfc3030, 0x30303030, 0x30300000, };
static const uint32_t profont22_67[] = { 0x3fdffe0f, 0x03c0f03c, 0x0f837fcf, 0xf00c073f, 0x8fc00000, };
static const uint32_t profont22_68[] = { 0xc0300c03, 0x00ff3fec, 0x1f03c0f0, 0x3c0f03c0, 0xf0300000, };
static const uint32_t profont22_69[] = { 0x30c000f3, 0xc30c30c3, 0x0cfff000, };
static const uint32_t profont22_6a[] = { 0x0c30003c, 0xf0c30c30, 0xc30c30c7, 0xfbc00000, };
static const uint32_t profont22_6b[] = { 0xc0300c03, 0x00c3b1cc, 0xe370fc3f, 0x8e730ec1, 0xf0300000, };
static const uint32_t profont22_6c[] = { 0xf3c30c30, 0xc30c30c3, 0x0cfff000, };
static const uint32_t profont22_6d[] = { 0xff3fecdf, 0x33ccf33c, 0xcf33ccf3, 0x30000000, };
static const uint32_t profont22_6e[] = { 0xcf37ef9f, 0xc3e0f03c, 0x0f03c0f0, 0x30000000, };
static const uint32_t profont22_6f[] = { 0x3f1fee1f, 0x03c0f03c, 0x0f877f8f, 0xc0000000, };
static const uint32_t profont22_70[] = { 0xff3fec1f, 0x03c0f03c, 0x0f07ffbf, 0xcc0300c0, 0x30000000, };
static const uint32_t profont22_71[] = { 0x3fdffe0f, 0x03c0f03c, 0x0f837fcf, 0xf00c0300, 0xc0300000, };
static const uint32_t profont22_72[] = { 0xcf37ef9f, 0xc3e0300c, 0x0300c030, 0x00000000, };
static const uint32_t profont22_73[] = { 0x3fdffc03, 0x007f0fe0, 0x0c03ffbf, 0xc0000000, };
static const uint32_t profont22_74[] = { 0x30303030, 0xfcfc3030, 0x30303038, 0x1f0f0000, };
static const uint32_t profont22_75[] = { 0xc0f03c0f, 0x03c0f07c, 0x3f9f7ecf, 0x30000000, };
static const uint32_t profont22_76[] = { 0xc0f03c0d, 0x86618ce3, 0x30781e03, 0x00000000, };
static const uint32_t profont22_77[] = { 0xccf33ccf, 0x33ccf33c, 0xcf337f8c, 0xc0000000, };
static const uint32_t profont22_78[] = { 0xc0f87738, 0xfc1e0783, 0xf1cee1f0, 0x30000000, };
static const uint32_t profont22_79[] = { 0xc0f03c0f, 0x03c0f03c, 0x0f837fcf, 0xf00c073f, 0x8fc00000, };
static const uint32_t profont22_7a[] = { 0xfffff038, 0x1c0e0703, 0x81c0ffff, 0xf0000000, };
static const uint32_t profont22_7b[] = { 0x0c738c30, 0xc30c31ce, 0x3870c30c, 0x30c30e1c, 0x30000000, };
static const uint32_t profont22_7c[] = { 0xffffffff, 0xf0000000, };
static const uint32_t profont22_7d[] = { 0xc3870c30, 0xc30c30e1, 0xc738c30c, 0x30c31ce3, 0x00000000, };
static const uint32_t profont22_7e[] = { 0x30df3cfb, 0x0c000000, };
static const uint32_t profont22_82[] = { 0x33337e40, };
static const uint32_t profont22_83[] = { 0x03c1f0e0, 0x300c0300, 0xc0303f0f, 0xc0c0300c, 0x0300c030, 0x0c0300c0, 0x70f83c00, };
static const uint32_t profont22_84[] = { 0x33333333, 0x77ee4400, };
static const uint32_t profont22_85[] = { 0xccf33000, };
static const uint32_t profont22_86[] = { 0x30cfff30, 0xc30c30c0, };
static const uint32_t profont22_87[] = { 0x30cfff30, 0xcfff30c0, };
static const uint32_t profont22_88[] = { 0x31eff300, };
static const uint32_t profont22_89[] = { 0x3ff7ffcc, 0xecdccf8c, 0xf07e03c0, 0x3cc7fef3, 0x3f33b333, 0x331fe0cc, };
static const uint32_t profont22_8a[] = { 0x330fc1e0, 0x303f1fee, 0x1f03c038, 0x07f0fe01, 0xc03c0f87, 0x7f8fc000, };
static const uint32_t profont22_8b[] = { 0x376ecce6, 0x73000000, };
static const uint32_t profont22_8c[] = { 0x3fdffec3, 0x30cc330c, 0xf33ccc33, 0x0cc3b07f, 0xcff00000, };
static const uint32_t profont22_91[] = { 0x27ecccc0, };
static const uint32_t profont22_92[] = { 0x33337e40, };
static const uint32_t profont22_93[] = { 0x2277eecc, 0xcccccc00, };
static const uint32_t profont22_94[] = { 0x33333333, 0x77ee4400, };
static const uint32_t profont22_95[] = { 0x1e1fe7fb, 0xffffffff, 0xfdfe7f87, 0x80000000, };
static const uint32_t profont22_96[] = { 0xfff00000, };
static const uint32_t profont22_97[] = { 0xffffff00, };
static const uint32_t profont22_98[] = { 0x30df3cfb, 0x0c000000, };
static const uint32_t profont22_99[] = { 0xff3fff33, 0xf33f3333, 0x33000000, };
static const uint32_t profont22_9a[] = { 0x330fc1e0, 0x30000003, 0xfdffc030, 0x07f0fe00, 0xc03ffbfc, };
static const uint32_t profont22_9b[] = { 0xce673376, 0xec000000, };
static const uint32_t profont22_9c[] = { 0x331feccf, 0x33cff3fc, 0xc3307fcc, 0xf0000000, };
static const uint32_t profont22_9f[] = { 0x330cc000, 0x00c0f03c, 0x0f03c0f8, 0x7738fc1e, 0x0300c030, 0x0c030000, };
static const uint32_t profont22_a1[] = { 0xf0fffff0, };
static const uint32_t profont22_a2[] = { 0x0c0303f1, 0xfeedf33c, 0xc330cc3b, 0x07fcff0c, 0x03000000, };
static const uint32_t profont22_a3[] = { 0x3c1f8e73, 0x0cc0300f, 0xc3f0c030, 0x0c0300c0, 0xf07ffbfc, };
static const uint32_t profont22_a4[] = { 0x40b877f8, 0xfc330cc3, 0xf1fee1d0, 0x20000000, };
static const uint32_t profont22_a5[] = { 0xc0f87738, 0xfcfffff0, 0xc030ffff, 0xf0c0300c, 0x03000000, };
static const uint32_t profont22_a6[] = { 0xffff0fff, 0xf0000000, };
static const uint32_t profont22_a7[] = { 0x1f1fe61f, 0x8370ce3d, 0xc338c738, 0xe71ce31c, 0xc3bc730e, 0xc1f867f8, 0xf8000000, };
static const uint32_t profont22_a8[] = { 0xcf300000, };
static const uint32_t profont22_a9[] = { 0x783f8870, 0x063d9f3c, 0x0f037ccf, 0x601a1cfe, 0x1e000000, };
static const uint32_t profont22_aa[] = { 0x3f7fe3c3, 0xc3e37f3f, 0x0000ffff, };
static const uint32_t profont22_ab[] = { 0x30dc761b, 0x8ec330ce, 0x398671cc, 0x30000000, };
static const uint32_t profont22_ac[] = { 0xfffff00c, 0x0300c030, };
static const uint32_t profont22_ad[] = { 0xfffff000, };
static const uint32_t profont22_ae[] = { 0x783f8870, 0x06f1be3c, 0xcf33f8fe, 0x7dfb3c00, };
static const uint32_t profont22_af[] = { 0xfff00000, };
static const uint32_t profont22_b0[] = { 0x3c7ee7c3, 0xc3e77e3c, };
static const uint32_t profont22_b1[] = { 0x0c0300c0, 0x30fffff0, 0xc0300c03, 0x0fffff00, };
static const uint32_t profont22_b2[] = { 0x74422223, 0xe0000000, };
static const uint32_t profont22_b3[] = { 0x744260c5, 0xc0000000, };
static const uint32_t profont22_b4[] = { 0x37ec0000, };
static const uint32_t profont22_b5[] = { 0xc330cc33, 0x0cc330cc, 0x331effff, 0x3c0300c0, 0x30000000, };
static const uint32_t profont22_b6[] = { 0x1fdff7cf, 0xb3ccf33e, 0xcdf37fc7, 0xf0cc330c, 0xc330cc33, };
static const uint32_t profont22_b7[] = { 0x6ff60000, };
static const uint32_t profont22_b8[] = { 0xff37e400, };
static const uint32_t profont22_b9[] = { 0x27084213, 0xe0000000, };
static const uint32_t profont22_ba[] = { 0x3c7ee7c3, 0xc3e77e3c, 0x0000ffff, };
static const uint32_t profont22_bb[] = { 0xc338e619, 0xc730cc37, 0x1d86e3b0, 0xc0000000, };
static const uint32_t profont22_bc[] = { 0x10070010, 0x01001011, 0x027c4008, 0x01002004, 0x008410c2, 0x1442483e, 0x00400e00, };
static const uint32_t profont22_bd[] = { 0x10070010, 0x01001011, 0x027c4008, 0x01002004, 0x009c1222, 0x02404808, 0x01003e00, };
static const uint32_t profont22_be[] = { 0x38044004, 0x01800414, 0x42384008, 0x01002004, 0x008410c2, 0x1442483e, 0x00400e00, };
static const uint32_t profont22_bf[] = { 0x0c030000, 0x000c0703, 0x81c0e030, 0x0c0f877f, 0x8fc00000, };
static const uint32_t profont22_c0[] = { 0x300e01c0, 0x300c0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c1[] = { 0x0301c0e0, 0x300c0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c2[] = { 0x0c0783f0, 0xcc0c0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c3[] = { 0x30df3cfb, 0x0c0c0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c4[] = { 0x330cc000, 0x000c0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c5[] = { 0x0c078330, 0xcc1e0781, 0xe0cc3318, 0x661b03ff, 0xfffc0f03, 0xc0f03000, };
static const uint32_t profont22_c6[] = { 0x3fdffec3, 0x30cc330f, 0xf3fccc33, 0x0cc330cf, 0xf3f00000, };
static const uint32_t profont22_c7[] = { 0x3f1fee1f, 0x03c0300c, 0x0300c030, 0x0c0f877f, 0x8fc0c070, 0x38040000, };
static const uint32_t profont22_c8[] = { 0x300e01c0, 0x30fffffc, 0x0300c030, 0x0ff3fcc0, 0x300c0300, 0xfffff000, };
static const uint32_t profont22_c9[] = { 0x0301c0e0, 0x30fffffc, 0x0300c030, 0x0ff3fcc0, 0x300c0300, 0xfffff000, };
static const uint32_t profont22_ca[] = { 0x0c0783f0, 0xccfffffc, 0x0300c030, 0x0ff3fcc0, 0x300c0300, 0xfffff000, };
static const uint32_t profont22_cb[] = { 0x330cc000, 0x00fffffc, 0x0300c030, 0x0ff3fcc0, 0x300c0300, 0xfffff000, };
static const uint32_t profont22_cc[] = { 0x300e01c0, 0x30fffff0, 0xc0300c03, 0x00c0300c, 0x0300c030, 0xfffff000, };
static const uint32_t profont22_cd[] = { 0x0301c0e0, 0x30fffff0, 0xc0300c03, 0x00c0300c, 0x0300c030, 0xfffff000, };
static const uint32_t profont22_ce[] = { 0x0c0783f0, 0xccfffff0, 0xc0300c03, 0x00c0300c, 0x0300c030, 0xfffff000, };
static const uint32_t profont22_cf[] = { 0x330cc000, 0x00fffff0, 0xc0300c03, 0x00c0300c, 0x0300c030, 0xfffff000, };
static const uint32_t profont22_d0[] = { 0x3f0fe31c, 0xc330cc3f, 0xcff330cc, 0x330cc73f, 0x8fc00000, };
static const uint32_t profont22_d1[] = { 0x30df3cfb, 0x1cc0f83f, 0x0fe3dcf3, 0xbc7f0fc1, 0xf03c0f03, 0xc0f03000, };
static const uint32_t profont22_d2[] = { 0x300e01c0, 0x303f1fee, 0x1f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_d3[] = { 0x0301c0e0, 0x303f1fee, 0x1f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_d4[] = { 0x0c0783f0, 0xcc000fc7, 0xfb87c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_d5[] = { 0x30df3cfb, 0x1c3f1fee, 0x1f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_d6[] = { 0x330cc000, 0x003f1fee, 0x1f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_d7[] = { 0x40b87738, 0xfc1e0783, 0xf1cee1d0, 0x20000000, };
static const uint32_t profont22_d8[] = { 0x3f1fee1f, 0x07c3f1fc, 0xef73f8fc, 0x3e0f877f, 0x8fc00000, };
static const uint32_t profont22_d9[] = { 0x300e01c0, 0x30c0f03c, 0x0f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_da[] = { 0x0301c0e0, 0x30c0f03c, 0x0f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_db[] = { 0x0c0783f0, 0xcc00303c, 0x0f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_dc[] = { 0x330cc000, 0x00c0f03c, 0x0f03c0f0, 0x3c0f03c0, 0xf03c0f87, 0x7f8fc000, };
static const uint32_t profont22_dd[] = { 0x0301c0e0, 0x30c0f03c, 0x0f03c0f8, 0x7738fc1e, 0x0300c030, 0x0c030000, };
static const uint32_t profont22_de[] = { 0xc0300ff3, 0xfec1f03c, 0x0f07ffbf, 0xcc0300c0, 0x30000000, };
static const uint32_t profont22_df[] = { 0x0f07e39d, 0xc3e0f07c, 0x3b0cc330, 0xec1f03c0, 0xf07cfb3c, 0xc0300000, };
static const uint32_t profont22_e0[] = { 0x0c038070, 0x0c000003, 0xfdffe0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_e1[] = { 0x0301c0e0, 0x30000003, 0xfdffe0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_e2[] = { 0x0c0783f0, 0xcc000003, 0xfdffe0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_e3[] = { 0x30df3cfb, 0x1c000003, 0xfdffe0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_e4[] = { 0x330cc000, 0x003fdffe, 0x0f03c0f0, 0x7c3f9f7e, 0xcf300000, };
static const uint32_t profont22_e5[] = { 0x0c078330, 0xcc1e0303, 0xfdffe0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_e6[] = { 0x3f1feedf, 0x33cff3fc, 0xc3b07fcf, 0xf0000000, };
static const uint32_t profont22_e7[] = { 0x3f1fee1f, 0x03c0300c, 0x03807fcf, 0xf0c07038, 0x04000000, };
static const uint32_t profont22_e8[] = { 0x300e01c0, 0x30000003, 0xf1fee1f0, 0x3fffffc0, 0x3807fcff, };
static const uint32_t profont22_e9[] = { 0x0301c0e0, 0x30000003, 0xf1fee1f0, 0x3fffffc0, 0x3807fcff, };
static const uint32_t profont22_ea[] = { 0x0c0783f0, 0xcc000003, 0xf1fee1f0, 0x3fffffc0, 0x3807fcff, };
static const uint32_t profont22_eb[] = { 0x330cc000, 0x003f1fee, 0x1f03ffff, 0xfc03807f, 0xcff00000, };
static const uint32_t profont22_ec[] = { 0xc3870c00, 0x0f3c30c3, 0x0c30cfff, };
static const uint32_t profont22_ed[] = { 0x0c738c00, 0x0f3c30c3, 0x0c30cfff, };
static const uint32_t profont22_ee[] = { 0x31eff300, 0x0f3c30c3, 0x0c30cfff, };
static const uint32_t profont22_ef[] = { 0xcf3000f3, 0xc30c30c3, 0x0cfff000, };
static const uint32_t profont22_f0[] = { 0x241f83c0, 0xf07e09c0, 0x38ff7ff8, 0x7c0f03c0, 0xf03e1dfe, 0x3f000000, };
static const uint32_t profont22_f1[] = { 0x30df3cfb, 0x1c00000c, 0xf37ef9fc, 0x3e0f03c0, 0xf03c0f03, };
static const uint32_t profont22_f2[] = { 0x300e01c0, 0x30000003, 0xf1fee1f0, 0x3c0f03c0, 0xf877f8fc, };
static const uint32_t profont22_f3[] = { 0x0301c0e0, 0x30000003, 0xf1fee1f0, 0x3c0f03c0, 0xf877f8fc, };
static const uint32_t profont22_f4[] = { 0x0c0783f0, 0xcc000003, 0xf1fee1f0, 0x3c0f03c0, 0xf877f8fc, };
static const uint32_t profont22_f5[] = { 0x30df3cfb, 0x1c000003, 0xf1fee1f0, 0x3c0f03c0, 0xf877f8fc, };
static const uint32_t profont22_f6[] = { 0x330cc000, 0x003f1fee, 0x1f03c0f0, 0x3c0f877f, 0x8fc00000, };
static const uint32_t profont22_f7[] = { 0x0c030000, 0x00fffff0, 0x00000c03, 0x00000000, };
static const uint32_t profont22_f8[] = { 0x3f1fee3f, 0x1fcef73f, 0x8fc77f8f, 0xc0000000, };
static const uint32_t profont22_f9[] = { 0x300e01c0, 0x3000000c, 0x0f03c0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_fa[] = { 0x0301c0e0, 0x3000000c, 0x0f03c0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_fb[] = { 0x0c0783f0, 0xcc00000c, 0x0f03c0f0, 0x3c0f07c3, 0xf9f7ecf3, };
static const uint32_t profont22_fc[] = { 0x330cc000, 0x00c0f03c, 0x0f03c0f0, 0x7c3f9f7e, 0xcf300000, };
static const uint32_t profont22_fd[] = { 0x0301c0e0, 0x3000000c, 0x0f03c0f0, 0x3c0f03c0, 0xf837fcff, 0x00c073f8, 0xfc000000, };
static const uint32_t profont22_fe[] = { 0xc0300c03, 0x00ff3fec, 0x1f03c0f0, 0x3c0f07ff, 0xbfcc0300, 0xc0300000, };
static const uint32_t profont22_ff[] = { 0x330cc000, 0x00c0f03c, 0x0f03c0f0, 0x3c0f837f, 0xcff00c07, 0x3f8fc000, };
static const uint32_t profont22_null[] = { 0 };

const struct font profont22 = {
	.ascent = 18,
	.descent = -4,
	.glyphs = {
		   {0, 0, 0, 0, 12, profont22_null},	// 0x00
		   {0, 0, 0, 0, 12, profont22_null},	// 0x01
		   {0, 0, 0, 0, 12, profont22_null},	// 0x02
		   {0, 0, 0, 0, 12, profont22_null},	// 0x03
		   {0, 0, 0, 0, 12, profont22_null},	// 0x04
		   {0, 0, 0, 0, 12, profont22_null},	// 0x05
		   {0, 0, 0, 0, 12, profont22_null},	// 0x06
		   {0, 0, 0, 0, 12, profont22_null},	// 0x07
		   {0, 0, 0, 0, 12, profont22_null},	// 0x08
		   {0, 0, 0, 0, 12, profont22_null},	// 0x09
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0a
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0b
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0c
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0d
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0e
		   {0, 0, 0, 0, 12, profont22_null},	// 0x0f
		   {0, 0, 0, 0, 12, profont22_null},	// 0x10
		   {0, 0, 0, 0, 12, profont22_null},	// 0x11
		   {0, 0, 0, 0, 12, profont22_null},	// 0x12
		   {0, 0, 0, 0, 12, profont22_null},	// 0x13
		   {0, 0, 0, 0, 12, profont22_null},	// 0x14
		   {0, 0, 0, 0, 12, profont22_null},	// 0x15
		   {0, 0, 0, 0, 12, profont22_null},	// 0x16
		   {0, 0, 0, 0, 12, profont22_null},	// 0x17
		   {0, 0, 0, 0, 12, profont22_null},	// 0x18
		   {0, 0, 0, 0, 12, profont22_null},	// 0x19
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1a
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1b
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1c
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1d
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1e
		   {0, 0, 0, 0, 12, profont22_null},	// 0x1f
		   {0, 0, 0, 0, 12, profont22_null},	// 0x20
		   {2, 14, 4, 0, 12, profont22_21},	// 0x21
		   {6, 6, 2, 10, 12, profont22_22},	// 0x22
		   {10, 10, 0, 4, 12, profont22_23},	// 0x23
		   {10, 18, 0, -2, 12, profont22_24},	// 0x24
		   {10, 14, 0, 0, 12, profont22_25},	// 0x25
		   {10, 14, 0, 0, 12, profont22_26},	// 0x26
		   {2, 6, 4, 10, 12, profont22_27},	// 0x27
		   {6, 18, 2, -2, 12, profont22_28},	// 0x28
		   {6, 18, 2, -2, 12, profont22_29},	// 0x29
		   {10, 10, 0, 4, 12, profont22_2a},	// 0x2a
		   {10, 10, 0, 2, 12, profont22_2b},	// 0x2b
		   {5, 9, 2, -4, 12, profont22_2c},	// 0x2c
		   {6, 2, 2, 6, 12, profont22_2d},	// 0x2d
		   {4, 4, 3, 1, 12, profont22_2e},	// 0x2e
		   {11, 20, 0, -4, 12, profont22_2f},	// 0x2f
		   {10, 14, 0, 0, 12, profont22_30},	// 0x30
		   {10, 14, 0, 0, 12, profont22_31},	// 0x31
		   {10, 14, 0, 0, 12, profont22_32},	// 0x32
		   {10, 14, 0, 0, 12, profont22_33},	// 0x33
		   {10, 14, 0, 0, 12, profont22_34},	// 0x34
		   {10, 14, 0, 0, 12, profont22_35},	// 0x35
		   {10, 14, 0, 0, 12, profont22_36},	// 0x36
		   {10, 14, 0, 0, 12, profont22_37},	// 0x37
		   {10, 14, 0, 0, 12, profont22_38},	// 0x38
		   {10, 14, 0, 0, 12, profont22_39},	// 0x39
		   {4, 10, 3, 1, 12, profont22_3a},	// 0x3a
		   {5, 15, 2, -4, 12, profont22_3b},	// 0x3b
		   {8, 14, 2, 0, 12, profont22_3c},	// 0x3c
		   {10, 6, 0, 4, 12, profont22_3d},	// 0x3d
		   {8, 14, 2, 0, 12, profont22_3e},	// 0x3e
		   {10, 14, 0, 0, 12, profont22_3f},	// 0x3f
		   {10, 14, 0, 0, 12, profont22_40},	// 0x40
		   {10, 14, 0, 0, 12, profont22_41},	// 0x41
		   {10, 14, 0, 0, 12, profont22_42},	// 0x42
		   {10, 14, 0, 0, 12, profont22_43},	// 0x43
		   {10, 14, 0, 0, 12, profont22_44},	// 0x44
		   {10, 14, 0, 0, 12, profont22_45},	// 0x45
		   {10, 14, 0, 0, 12, profont22_46},	// 0x46
		   {10, 14, 0, 0, 12, profont22_47},	// 0x47
		   {10, 14, 0, 0, 12, profont22_48},	// 0x48
		   {10, 14, 0, 0, 12, profont22_49},	// 0x49
		   {10, 14, 0, 0, 12, profont22_4a},	// 0x4a
		   {10, 14, 0, 0, 12, profont22_4b},	// 0x4b
		   {10, 14, 0, 0, 12, profont22_4c},	// 0x4c
		   {10, 14, 0, 0, 12, profont22_4d},	// 0x4d
		   {10, 14, 0, 0, 12, profont22_4e},	// 0x4e
		   {10, 14, 0, 0, 12, profont22_4f},	// 0x4f
		   {10, 14, 0, 0, 12, profont22_50},	// 0x50
		   {10, 16, 0, -2, 12, profont22_51},	// 0x51
		   {10, 14, 0, 0, 12, profont22_52},	// 0x52
		   {10, 14, 0, 0, 12, profont22_53},	// 0x53
		   {10, 14, 0, 0, 12, profont22_54},	// 0x54
		   {10, 14, 0, 0, 12, profont22_55},	// 0x55
		   {10, 14, 0, 0, 12, profont22_56},	// 0x56
		   {10, 14, 0, 0, 12, profont22_57},	// 0x57
		   {10, 14, 0, 0, 12, profont22_58},	// 0x58
		   {10, 14, 0, 0, 12, profont22_59},	// 0x59
		   {10, 14, 0, 0, 12, profont22_5a},	// 0x5a
		   {4, 18, 4, -2, 12, profont22_5b},	// 0x5b
		   {11, 20, 1, -4, 12, profont22_5c},	// 0x5c
		   {4, 18, 2, -2, 12, profont22_5d},	// 0x5d
		   {10, 6, 0, 8, 12, profont22_5e},	// 0x5e
		   {12, 2, 0, -4, 12, profont22_5f},	// 0x5f
		   {4, 4, 2, 12, 12, profont22_60},	// 0x60
		   {10, 10, 0, 0, 12, profont22_61},	// 0x61
		   {10, 14, 0, 0, 12, profont22_62},	// 0x62
		   {10, 10, 0, 0, 12, profont22_63},	// 0x63
		   {10, 14, 0, 0, 12, profont22_64},	// 0x64
		   {10, 10, 0, 0, 12, profont22_65},	// 0x65
		   {8, 14, 2, 0, 12, profont22_66},	// 0x66
		   {10, 14, 0, -4, 12, profont22_67},	// 0x67
		   {10, 14, 0, 0, 12, profont22_68},	// 0x68
		   {6, 14, 2, 0, 12, profont22_69},	// 0x69
		   {6, 18, 0, -4, 12, profont22_6a},	// 0x6a
		   {10, 14, 0, 0, 12, profont22_6b},	// 0x6b
		   {6, 14, 2, 0, 12, profont22_6c},	// 0x6c
		   {10, 10, 0, 0, 12, profont22_6d},	// 0x6d
		   {10, 10, 0, 0, 12, profont22_6e},	// 0x6e
		   {10, 10, 0, 0, 12, profont22_6f},	// 0x6f
		   {10, 14, 0, -4, 12, profont22_70},	// 0x70
		   {10, 14, 0, -4, 12, profont22_71},	// 0x71
		   {10, 10, 0, 0, 12, profont22_72},	// 0x72
		   {10, 10, 0, 0, 12, profont22_73},	// 0x73
		   {8, 14, 2, 0, 12, profont22_74},	// 0x74
		   {10, 10, 0, 0, 12, profont22_75},	// 0x75
		   {10, 10, 0, 0, 12, profont22_76},	// 0x76
		   {10, 10, 0, 0, 12, profont22_77},	// 0x77
		   {10, 10, 0, 0, 12, profont22_78},	// 0x78
		   {10, 14, 0, -4, 12, profont22_79},	// 0x79
		   {10, 10, 0, 0, 12, profont22_7a},	// 0x7a
		   {6, 22, 2, -4, 12, profont22_7b},	// 0x7b
		   {2, 18, 4, -2, 12, profont22_7c},	// 0x7c
		   {6, 22, 2, -4, 12, profont22_7d},	// 0x7d
		   {10, 4, 0, 6, 12, profont22_7e},	// 0x7e
		   {0, 0, 0, 0, 12, profont22_null},	// 0x7f
		   {0, 0, 0, 0, 12, profont22_null},	// 0x80
		   {0, 0, 0, 0, 12, profont22_null},	// 0x81
		   {4, 7, 0, -3, 12, profont22_82},	// 0x82
		   {10, 22, 0, -4, 12, profont22_83},	// 0x83
		   {8, 7, 0, -3, 12, profont22_84},	// 0x84
		   {10, 2, 0, 0, 12, profont22_85},	// 0x85
		   {6, 10, 2, 4, 12, profont22_86},	// 0x86
		   {6, 10, 2, 4, 12, profont22_87},	// 0x87
		   {6, 4, 2, 12, 12, profont22_88},	// 0x88
		   {12, 16, 0, 0, 12, profont22_89},	// 0x89
		   {10, 18, 0, 0, 12, profont22_8a},	// 0x8a
		   {4, 10, 0, -1, 12, profont22_8b},	// 0x8b
		   {10, 14, 0, 0, 12, profont22_8c},	// 0x8c
		   {0, 0, 0, 0, 12, profont22_null},	// 0x8d
		   {0, 0, 0, 0, 12, profont22_null},	// 0x8e
		   {0, 0, 0, 0, 12, profont22_null},	// 0x8f
		   {0, 0, 0, 0, 12, profont22_null},	// 0x90
		   {4, 7, 4, 8, 12, profont22_91},	// 0x91
		   {4, 7, 4, 7, 12, profont22_92},	// 0x92
		   {8, 7, 2, 8, 12, profont22_93},	// 0x93
		   {8, 7, 2, 7, 12, profont22_94},	// 0x94
		   {10, 10, 0, 2, 12, profont22_95},	// 0x95
		   {6, 2, 2, 6, 12, profont22_96},	// 0x96
		   {12, 2, 0, 6, 12, profont22_97},	// 0x97
		   {10, 4, 0, 12, 12, profont22_98},	// 0x98
		   {12, 6, 0, 8, 12, profont22_99},	// 0x99
		   {10, 16, 0, 0, 12, profont22_9a},	// 0x9a
		   {4, 10, 0, -1, 12, profont22_9b},	// 0x9b
		   {10, 10, 0, 0, 12, profont22_9c},	// 0x9c
		   {0, 0, 0, 0, 12, profont22_null},	// 0x9d
		   {0, 0, 0, 0, 12, profont22_null},	// 0x9e
		   {10, 18, 0, 0, 12, profont22_9f},	// 0x9f
		   {0, 0, 0, 0, 12, profont22_null},	// 0xa0
		   {2, 14, 6, 0, 12, profont22_a1},	// 0xa1
		   {10, 14, 0, -2, 12, profont22_a2},	// 0xa2
		   {10, 16, 0, 0, 12, profont22_a3},	// 0xa3
		   {10, 10, 0, 0, 12, profont22_a4},	// 0xa4
		   {10, 14, 0, 0, 12, profont22_a5},	// 0xa5
		   {2, 18, 4, -2, 12, profont22_a6},	// 0xa6
		   {10, 20, 0, -2, 12, profont22_a7},	// 0xa7
		   {6, 2, 2, 12, 12, profont22_a8},	// 0xa8
		   {10, 14, 0, 0, 12, profont22_a9},	// 0xa9
		   {8, 12, 2, 6, 12, profont22_aa},	// 0xaa
		   {10, 10, 0, -1, 12, profont22_ab},	// 0xab
		   {10, 6, 0, 2, 12, profont22_ac},	// 0xac
		   {10, 2, 0, 6, 12, profont22_ad},	// 0xad
		   {10, 12, 0, 2, 12, profont22_ae},	// 0xae
		   {6, 2, 2, 12, 12, profont22_af},	// 0xaf
		   {8, 8, 2, 8, 12, profont22_b0},	// 0xb0
		   {10, 12, 0, 0, 12, profont22_b1},	// 0xb1
		   {5, 7, 3, 11, 12, profont22_b2},	// 0xb2
		   {5, 7, 3, 11, 12, profont22_b3},	// 0xb3
		   {4, 4, 4, 12, 12, profont22_b4},	// 0xb4
		   {10, 14, 0, -4, 12, profont22_b5},	// 0xb5
		   {10, 16, 0, 0, 12, profont22_b6},	// 0xb6
		   {4, 4, 4, 4, 12, profont22_b7},	// 0xb7
		   {4, 6, 2, -4, 12, profont22_b8},	// 0xb8
		   {5, 7, 3, 11, 12, profont22_b9},	// 0xb9
		   {8, 12, 2, 6, 12, profont22_ba},	// 0xba
		   {10, 10, 0, -1, 12, profont22_bb},	// 0xbb
		   {12, 18, 0, 0, 12, profont22_bc},	// 0xbc
		   {12, 18, 0, 0, 12, profont22_bd},	// 0xbd
		   {12, 18, 0, 0, 12, profont22_be},	// 0xbe
		   {10, 14, 0, 0, 12, profont22_bf},	// 0xbf
		   {10, 18, 0, 0, 12, profont22_c0},	// 0xc0
		   {10, 18, 0, 0, 12, profont22_c1},	// 0xc1
		   {10, 18, 0, 0, 12, profont22_c2},	// 0xc2
		   {10, 18, 0, 0, 12, profont22_c3},	// 0xc3
		   {10, 18, 0, 0, 12, profont22_c4},	// 0xc4
		   {10, 18, 0, 0, 12, profont22_c5},	// 0xc5
		   {10, 14, 0, 0, 12, profont22_c6},	// 0xc6
		   {10, 18, 0, -4, 12, profont22_c7},	// 0xc7
		   {10, 18, 0, 0, 12, profont22_c8},	// 0xc8
		   {10, 18, 0, 0, 12, profont22_c9},	// 0xc9
		   {10, 18, 0, 0, 12, profont22_ca},	// 0xca
		   {10, 18, 0, 0, 12, profont22_cb},	// 0xcb
		   {10, 18, 0, 0, 12, profont22_cc},	// 0xcc
		   {10, 18, 0, 0, 12, profont22_cd},	// 0xcd
		   {10, 18, 0, 0, 12, profont22_ce},	// 0xce
		   {10, 18, 0, 0, 12, profont22_cf},	// 0xcf
		   {10, 14, 0, 0, 12, profont22_d0},	// 0xd0
		   {10, 18, 0, 0, 12, profont22_d1},	// 0xd1
		   {10, 18, 0, 0, 12, profont22_d2},	// 0xd2
		   {10, 18, 0, 0, 12, profont22_d3},	// 0xd3
		   {10, 18, 0, 0, 12, profont22_d4},	// 0xd4
		   {10, 18, 0, 0, 12, profont22_d5},	// 0xd5
		   {10, 18, 0, 0, 12, profont22_d6},	// 0xd6
		   {10, 10, 0, 2, 12, profont22_d7},	// 0xd7
		   {10, 14, 0, 0, 12, profont22_d8},	// 0xd8
		   {10, 18, 0, 0, 12, profont22_d9},	// 0xd9
		   {10, 18, 0, 0, 12, profont22_da},	// 0xda
		   {10, 18, 0, 0, 12, profont22_db},	// 0xdb
		   {10, 18, 0, 0, 12, profont22_dc},	// 0xdc
		   {10, 18, 0, 0, 12, profont22_dd},	// 0xdd
		   {10, 14, 0, 0, 12, profont22_de},	// 0xde
		   {10, 18, 0, -2, 12, profont22_df},	// 0xdf
		   {10, 16, 0, 0, 12, profont22_e0},	// 0xe0
		   {10, 16, 0, 0, 12, profont22_e1},	// 0xe1
		   {10, 16, 0, 0, 12, profont22_e2},	// 0xe2
		   {10, 16, 0, 0, 12, profont22_e3},	// 0xe3
		   {10, 14, 0, 0, 12, profont22_e4},	// 0xe4
		   {10, 16, 0, 0, 12, profont22_e5},	// 0xe5
		   {10, 10, 0, 0, 12, profont22_e6},	// 0xe6
		   {10, 14, 0, -4, 12, profont22_e7},	// 0xe7
		   {10, 16, 0, 0, 12, profont22_e8},	// 0xe8
		   {10, 16, 0, 0, 12, profont22_e9},	// 0xe9
		   {10, 16, 0, 0, 12, profont22_ea},	// 0xea
		   {10, 14, 0, 0, 12, profont22_eb},	// 0xeb
		   {6, 16, 2, 0, 12, profont22_ec},	// 0xec
		   {6, 16, 2, 0, 12, profont22_ed},	// 0xed
		   {6, 16, 2, 0, 12, profont22_ee},	// 0xee
		   {6, 14, 2, 0, 12, profont22_ef},	// 0xef
		   {10, 17, 0, 0, 12, profont22_f0},	// 0xf0
		   {10, 16, 0, 0, 12, profont22_f1},	// 0xf1
		   {10, 16, 0, 0, 12, profont22_f2},	// 0xf2
		   {10, 16, 0, 0, 12, profont22_f3},	// 0xf3
		   {10, 16, 0, 0, 12, profont22_f4},	// 0xf4
		   {10, 16, 0, 0, 12, profont22_f5},	// 0xf5
		   {10, 14, 0, 0, 12, profont22_f6},	// 0xf6
		   {10, 10, 0, 2, 12, profont22_f7},	// 0xf7
		   {10, 10, 0, 0, 12, profont22_f8},	// 0xf8
		   {10, 16, 0, 0, 12, profont22_f9},	// 0xf9
		   {10, 16, 0, 0, 12, profont22_fa},	// 0xfa
		   {10, 16, 0, 0, 12, profont22_fb},	// 0xfb
		   {10, 14, 0, 0, 12, profont22_fc},	// 0xfc
		   {10, 20, 0, -4, 12, profont22_fd},	// 0xfd
		   {10, 18, 0, -4, 12, profont22_fe},	// 0xfe
		   {10, 18, 0, -4, 12, profont22_ff},	// 0xff
		   },
};
